## Exploration données batiments

[COLLECTE] Données date construction bâtiments
https://mattermost.services.dataforgood.fr/boards/team/4g8gayrar3r5d8ofobpk9kaxkr/bjjws538jrir4zxuh35r9kr35qo/vpki6pz3czj89fkjgth3kbq659r/cfti645hma3nbjn6woxwp7t9q9o

In [1]:
import pandas as pd
import numpy as np

In [10]:
bat = pd.read_csv('../csv/DS_RP_LOGEMENT_PRINC_2022_data.csv', delimiter=';')
bat.info()

/var/folders/wb/bg23zgwj389404sv03x64x2m0000gn/T/ipykernel_81684/794499090.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  bat = pd.read_csv('../csv/DS_RP_LOGEMENT_PRINC_2022_data.csv', delimiter=';')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8983400 entries, 0 to 8983399
Data columns (total 14 columns):
 #   Column       Dtype
---  ------       -----
 0   BUILD_END    object
 1   CARPARK      object
 2   CARS         object
 3   GEO          object
 4   GEO_OBJECT   object
 5   L_STAY       object
 6   NOR          object
 7   NRG_SRC      object
 8   OCS          object
 9   RP_MEASURE   object
 10  TDW          object
 11  TSH          object
 12  TIME_PERIOD  int64
 13  OBS_VALUE    float64
dtypes: float64(1), int64(1), object(12)
memory usage: 959.5+ MB

In [11]:
bat_bdx = bat[
    (bat.GEO == '13055') &
    # (bat.GEO_OBJECT == 'COM') &
    (bat.TIME_PERIOD == 2022)]

In [13]:
bat_bdx.GEO_OBJECT.unique()

array(['BV2022', 'COM'], dtype=object)

In [3]:
bat_bdx = bat[
    (bat.GEO == '33063') &
    (bat.GEO_OBJECT == 'COM') &
    (bat.TIME_PERIOD == 2022)]

bat_bdx.head()

,BUILD_END,CARPARK,CARS,GEO,GEO_OBJECT,L_STAY,NOR,NRG_SRC,OCS,RP_MEASURE,TDW,TSH,TIME_PERIOD,OBS_VALUE
3875229,_T,_T,_T,33063,COM,_T,_T,_T,DW_VAC,DWELLINGS,3T6,_T,2022,25.91203
3986726,_T,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,114015.48661
3988000,_T,_T,_T,33063,COM,_T,_T,_T,DW_VAC,DWELLINGS,2,_T,2022,10139.17129
3989482,_T,_T,_T,33063,COM,_T,_T,_T,DW_SEC_DW_OCC,DWELLINGS,2,_T,2022,8676.67451
3992361,_T,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,31674.76996

In [4]:
bat_bdx[~(bat_bdx.BUILD_END == '_T')]

,BUILD_END,CARPARK,CARS,GEO,GEO_OBJECT,L_STAY,NOR,NRG_SRC,OCS,RP_MEASURE,TDW,TSH,TIME_PERIOD,OBS_VALUE
5500120,Y1946T1970,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,5973.98528
5500432,Y2006TAAAA,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,18198.23176
5501268,Y1971T1990,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,25380.62653
5501547,Y2006TAAAA,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,168.81691
5502903,Y1946T1970,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,19035.98655
5505961,Y1991T2005,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,17420.45783
5524174,Y1919T1945,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,8920.01887
5525816,Y1971T1990,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,153.39615
5526492,Y1919T1945,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,7638.10558
5526995,Y1991T2005,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,249.08478
5526996,Y1946T1970,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,83.37428
5559653,Y1971T1990,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,3166.75681
5560072,Y2006TAAAA,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,1739.63030
5560870,Y_LT1919,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,2,_T,2022,22782.19507
5562060,Y_LT1919,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,80.06968
5562126,Y_LT1919,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,10370.73829
5562285,Y1919T1945,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,3T6,_T,2022,72.96064
5562994,Y1991T2005,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,1,_T,2022,2582.09655
6338216,Y1919T1945,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,16631.08509
6343856,Y_LT1919,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,33233.00304
6345770,Y1991T2005,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,20251.63916
6346197,Y1946T1970,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,25093.34612
6349704,Y1971T1990,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,28700.77949
6352077,Y2006TAAAA,_T,_T,33063,COM,_T,_T,_T,DW_MAIN,DWELLINGS,_T,_T,2022,20106.67897

In [5]:
bat.head()

,BUILD_END,CARPARK,CARS,GEO,GEO_OBJECT,L_STAY,NOR,NRG_SRC,OCS,RP_MEASURE,TDW,TSH,TIME_PERIOD,OBS_VALUE
0,_T,_T,_T,64265,COM,_T,_T,OTH,DW_MAIN,DWELLINGS,_T,_T,2016,20.25000
1,_T,_T,_T,60343,COM,_T,_T,ELC,DW_MAIN,DWELLINGS,_T,_T,2016,96.38595
2,_T,_T,_T,625,ARR,_T,R1,_T,DW_MAIN,DWELLINGS,_T,_T,2011,988.76189
3,_T,_T,_T,133,ARR,_T,R1,_T,DW_MAIN,DWELLINGS,_T,_T,2011,34650.54961
4,_T,_T,_T,63398,COM,_T,_T,ELC,DW_MAIN,DWELLINGS,_T,_T,2016,1.97938

In [6]:
bat_com = bat[
    ~(bat.BUILD_END == '_T') &      # On ignore les totaux qui donnent des découpages selon d'autres axes d'analyses
    ~(bat.TDW == '_T') &            # Type de logement (On ignore le total pour ne pas compter deux fois) 
    (bat.GEO_OBJECT == 'COM') &     # On ne garde que les communes (attention pour les PLM)
    (bat.TIME_PERIOD == 2022)     # Pour l'instant on ne garde que la denière année (2022)
] 
bat_com.info()

<class 'pandas.core.frame.DataFrame'>
Index: 358919 entries, 3853780 to 6549873
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   BUILD_END    358919 non-null  object
 1   CARPARK      358919 non-null  object
 2   CARS         358919 non-null  object
 3   GEO          358919 non-null  object
 4   GEO_OBJECT   358919 non-null  object
 5   L_STAY       358919 non-null  object
 6   NOR          358919 non-null  object
 7   NRG_SRC      358919 non-null  object
 8   OCS          358919 non-null  object
 9   RP_MEASURE   358919 non-null  object
 10  TDW          358919 non-null  object
 11  TSH          358919 non-null  object
 12  TIME_PERIOD  358919 non-null  int64
 13  OBS_VALUE    358919 non-null  float64
dtypes: float64(1), int64(1), object(12)
memory usage: 41.1+ MB

In [7]:
del bat #save memory

In [8]:
bat_com_agg = bat_com[['GEO', 'BUILD_END','OBS_VALUE']].groupby(['GEO', 'BUILD_END']).sum('OBS_VALUE').reset_index()
bat_com_agg = bat_com_agg.pivot_table(index='GEO', columns=['BUILD_END'], values='OBS_VALUE').reset_index()
year_col = [col for col in bat_com_agg.columns.values if col.startswith('Y')]
bat_com_agg['Total'] = bat_com_agg[year_col].sum(axis=1)
bat_com_agg.head()

BUILD_END,GEO,Y1919T1945,Y1946T1970,Y1971T1990,Y1991T2005,Y2006TAAAA,Y_LT1919,Total
0,01001,22.00000,15.00000,100.00000,88.00000,37.00000,77.00000,339.00000
1,01002,6.00000,13.00000,9.00000,10.00000,20.00000,61.00000,119.00000
2,01004,382.08249,1353.83441,1759.04881,1412.05155,1760.49638,340.19455,7007.70819
3,01005,36.15079,83.04341,217.29169,149.04367,212.80010,111.83214,810.16180
4,01006,5.00000,5.00000,10.00000,9.00000,12.00000,16.00000,57.00000

In [16]:
bat_com_agg.head()

BUILD_END,GEO,Y1919T1945,Y1946T1970,Y1971T1990,Y1991T2005,Y2006TAAAA,Y_LT1919,Total
0,01001,22.00000,15.00000,100.00000,88.00000,37.00000,77.00000,"[Y1919T1945, Y1946T1970, Y1971T1990, Y1991T200..."
1,01002,6.00000,13.00000,9.00000,10.00000,20.00000,61.00000,"[Y1919T1945, Y1946T1970, Y1971T1990, Y1991T200..."
2,01004,382.08249,1353.83441,1759.04881,1412.05155,1760.49638,340.19455,"[Y1919T1945, Y1946T1970, Y1971T1990, Y1991T200..."
3,01005,36.15079,83.04341,217.29169,149.04367,212.80010,111.83214,"[Y1919T1945, Y1946T1970, Y1971T1990, Y1991T200..."
4,01006,5.00000,5.00000,10.00000,9.00000,12.00000,16.00000,"[Y1919T1945, Y1946T1970, Y1971T1990, Y1991T200..."

In [ ]:
bat_com_agg[bat_com_agg.GEO == '33063']

BUILD_END,GEO,Y1919T1945,Y1946T1970,Y1971T1990,Y1991T2005,Y2006TAAAA,Y_LT1919,_T
18994,33063,33262.17018,50186.69223,57401.55898,40503.27832,40213.35794,66466.00608,6.409187e+06

# Exploration base BNDB

## Approach 1 (Doesnt work)

Using the API with Open (free) plan we cannot fetch large amount of data. But this is an example of how it works below

In [14]:
import requests
r = requests.get(f'https://api.bdnb.io/v1/bdnb/donnees/batiment_groupe_risques',
                 params={   
                         'select': 'batiment_groupe_id, code_departement_insee, alea_argile',
                         'batiment_groupe_id': 'eq.bdnb-bg-GWH9-79G1-B81G',
                        #  'code_departement_insee': '33',
                         'limit': 5}                 
                 )
r.json()

[{'batiment_groupe_id': 'bdnb-bg-GWH9-79G1-B81G',
  'code_departement_insee': '33',
  'alea_argile': 'Moyen'}]

## Approach 2 (works)

We can use the BDNB dumps by département (PoC) or France entière that can be found here: https://bdnb.io/download/

Note: Because the file is huge (35Gb compressed) we leverage polars for data manipulation vs pandas

In [51]:
# Load necessary imports and variables
import zipfile
import tarfile
import polars as pl
import os
import shutil

# Configuration

# PoC (Ain)
# ARCHIVE_PATH = "../csv/open_data_millesime_2025-07-a_dep01_csv.zip"
# EXTRACT_DIR = "../csv/extracted_dep01"
# OUTPUT_FILE = "../csv/dep01_houses_poc.csv"

# France entière
ARCHIVE_PATH = "../csv/open_data_millesime_2025-07-a_france_csv.tar.gz"
EXTRACT_DIR = "../csv/extracted_france"
OUTPUT_FILE = "../csv/france_houses_agg.parquet"


# Relevant files in the archive (standard paths for France dump often have ./ prefixes or different nesting)
# We will search for these suffixes
REQUIRED_SUFFIXES = [
    "batiment_groupe.csv",
    "batiment_groupe_risques.csv",
    "batiment_groupe_ffo_bat.csv",
    "batiment_groupe_synthese_propriete_usage.csv"
]

In [52]:
# Extraction, join and agg functions
def get_file_map(archive_list):
    """Maps suffix to the full path in the archive."""
    file_map = {}
    for actual_path in archive_list:
        for suffix in REQUIRED_SUFFIXES:
            if actual_path.endswith(suffix):
                file_map[suffix] = actual_path
    return file_map

def extract_files():
    print(f"Opening archive {os.path.basename(ARCHIVE_PATH)}...")
    os.makedirs(EXTRACT_DIR, exist_ok=True)
    
    if ARCHIVE_PATH.endswith('.zip'):
        with zipfile.ZipFile(ARCHIVE_PATH, 'r') as z:
            file_map = get_file_map(z.namelist())
            for name, actual_path in file_map.items():
                print(f"  Extracting {actual_path}...")
                z.extract(actual_path, EXTRACT_DIR)
    
    elif ARCHIVE_PATH.endswith('.tar.gz') or ARCHIVE_PATH.endswith('.tgz'):
        with tarfile.open(ARCHIVE_PATH, 'r:gz') as t:
            file_map = get_file_map(t.getnames())
            for name, actual_path in file_map.items():
                print(f"  Extracting {actual_path}...")
                t.extract(actual_path, EXTRACT_DIR)
    
    return file_map

def get_construction_period():
    """Returns a Polars expression for construction period grouping (INSEE Standard)."""
    return (
        pl.when(pl.col("annee_construction").is_null()).then(pl.lit("Inconnue"))
        .when(pl.col("annee_construction") < 1915).then(pl.lit("Avant 1915"))
        .when(pl.col("annee_construction") < 1946).then(pl.lit("1916-1945"))
        .when(pl.col("annee_construction") < 1971).then(pl.lit("1946-1970"))
        .when(pl.col("annee_construction") < 1991).then(pl.lit("1971-1990"))
        .when(pl.col("annee_construction") < 2006).then(pl.lit("1991-2005"))
        .otherwise(pl.lit("Après 2006"))
        .alias("periode_construction")
    )

def process_data(file_map):
    print("\nProcessing data with Polars (v2 optimized - Aggregated)...")
    
    paths = {suffix: os.path.join(EXTRACT_DIR, actual_path) for suffix, actual_path in file_map.items()}
    
    # Use StringCache for efficient Categorical strings across tables
    with pl.StringCache():
        # 1. Start with Usage to filter early
        q_usage = (
            pl.scan_csv(paths['batiment_groupe_synthese_propriete_usage.csv'], separator=';', infer_schema_length=100000)
            .filter(pl.col("usage_principal_bdnb_open") == "Résidentiel individuel")
            .select("batiment_groupe_id") # We only need the IDs that match
        )
        
        # 2. Base table with commune codes (force string to avoid numeric parsing errors)
        q_base = (
            pl.scan_csv(paths['batiment_groupe.csv'], separator=';', 
                       infer_schema_length=100000, 
                       schema_overrides={"code_commune_insee": pl.String})
            .select(["batiment_groupe_id", "code_commune_insee"])
        )
        
        # 3. Risks
        q_risks = (
            pl.scan_csv(paths['batiment_groupe_risques.csv'], separator=';', infer_schema_length=100000)
            .select(["batiment_groupe_id", "alea_argile"])
        )
        
        # 4. Construction years
        q_ffo = (
            pl.scan_csv(paths['batiment_groupe_ffo_bat.csv'], separator=';', infer_schema_length=100000)
            .select(["batiment_groupe_id", "annee_construction"])
        )
        
        # Define Join & Transformation Plan
        plan = (
            q_usage
            .join(q_base, on="batiment_groupe_id", how="inner")
            .join(q_risks, on="batiment_groupe_id", how="left")
            .join(q_ffo, on="batiment_groupe_id", how="left")
            # SELECT and Transform columns as early as possible after joins
            .select(["code_commune_insee", "annee_construction", "alea_argile"])
            .with_columns([
                # Simplified elegant padding: always string, pad to 5
                pl.col("code_commune_insee").cast(pl.String).str.zfill(5),
                
                # Group into INSEE periods
                get_construction_period(),
                # Risk cleanup + categorical for memory efficiency
                pl.col("alea_argile").fill_null("Nul").cast(pl.Categorical)
            ])
            .drop("annee_construction") # Raw year no longer needed
        )
        
        # Define Aggregation Plan
        agg_plan = (
            plan.group_by(["code_commune_insee", "periode_construction", "alea_argile"])
            .agg(pl.len().alias("nb_maisons"))
            .sort(["code_commune_insee", "periode_construction"])
        )
        
        print("Executing streaming aggregation (v2 optimized). This may take several minutes...")
        # Engine streaming is best for 35GB datasets on standard hardware
        df_agg = agg_plan.collect(engine='streaming')
    
    print(f"\nNational Summary Preview:")
    print(df_agg.head(10))
    print(f"\nTotal aggregated rows: {len(df_agg)}")
    
    df_agg.write_parquet(OUTPUT_FILE)
    print(f"\nFinal results saved to {OUTPUT_FILE}")

In [53]:
# Run the script
if not os.path.exists(ARCHIVE_PATH):
    print(f"Error: Archive not found at {ARCHIVE_PATH}")
else:
    # Check if files already extracted
    # archive_names = []
    # if ARCHIVE_PATH.endswith('.zip'):
    #     with zipfile.ZipFile(ARCHIVE_PATH, 'r') as z: archive_names = z.namelist()
    # else:
    #     with tarfile.open(ARCHIVE_PATH, 'r:gz') as t: archive_names = t.getnames()
    
    file_map = {'batiment_groupe.csv': './csv/batiment_groupe.csv',
                'batiment_groupe_ffo_bat.csv': './csv/batiment_groupe_ffo_bat.csv',
                'batiment_groupe_risques.csv': './csv/batiment_groupe_risques.csv',
                'batiment_groupe_synthese_propriete_usage.csv': './csv/batiment_groupe_synthese_propriete_usage.csv'
                }
    
    # Determine if we need to extract
    needs_extract = False
    for suffix, actual_path in file_map.items():
        if not os.path.exists(os.path.join(EXTRACT_DIR, actual_path)):
            needs_extract = True
            break
    
    if needs_extract:
        file_map = extract_files()
    else:
        print("Required files already extracted.")
        
    process_data(file_map)

Required files already extracted.

Processing data with Polars (v2 optimized - Aggregated)...
Executing streaming aggregation (v2 optimized). This may take several minutes...

National Summary Preview:
shape: (10, 4)
┌────────────────────┬──────────────────────┬─────────────┬────────────┐
│ code_commune_insee ┆ periode_construction ┆ alea_argile ┆ nb_maisons │
│ ---                ┆ ---                  ┆ ---         ┆ ---        │
│ str                ┆ str                  ┆ cat         ┆ u32        │
╞════════════════════╪══════════════════════╪═════════════╪════════════╡
│ 01001              ┆ 1916-1945            ┆ Faible      ┆ 5          │
│ 01001              ┆ 1946-1970            ┆ Faible      ┆ 4          │
│ 01001              ┆ 1971-1990            ┆ Faible      ┆ 93         │
│ 01001              ┆ 1991-2005            ┆ Moyen       ┆ 1          │
│ 01001              ┆ 1991-2005            ┆ Faible      ┆ 78         │
│ 01001              ┆ Après 2006           ┆ Moyen       ┆ 2          │
│ 01001              ┆ Après 2006           ┆ Nul         ┆ 1          │
│ 01001              ┆ Après 2006           ┆ Faible      ┆ 49         │
│ 01001              ┆ Avant 1915           ┆ Moyen       ┆ 7          │
│ 01001              ┆ Avant 1915           ┆ Faible      ┆ 118        │
└────────────────────┴──────────────────────┴─────────────┴────────────┘

Total aggregated rows: 407350

Final results saved to ../csv/france_houses_agg.parquet

In [55]:
df_agg = pd.read_parquet("../csv/france_houses_agg.parquet")
df_agg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407350 entries, 0 to 407349
Data columns (total 4 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   code_commune_insee    407350 non-null  object
 1   periode_construction  407350 non-null  object
 2   alea_argile           407350 non-null  category
 3   nb_maisons            407350 non-null  uint32
dtypes: category(1), object(2), uint32(1)
memory usage: 8.2+ MB

In [56]:
df_agg[df_agg.code_commune_insee == '33063'].head(20)

       code_commune_insee periode_construction alea_argile  nb_maisons
141124              33063            1916-1945       Moyen        4523
141125              33063            1916-1945        Fort        2455
141126              33063            1916-1945         Nul          11
141127              33063            1946-1970        Fort        1064
141128              33063            1946-1970         Nul           7
141129              33063            1946-1970       Moyen        2484
141130              33063            1971-1990         Nul           3
141131              33063            1971-1990       Moyen        1202
141132              33063            1971-1990        Fort         486
141133              33063            1991-2005         Nul          61
141134              33063            1991-2005        Fort         481
141135              33063            1991-2005       Moyen         914
141136              33063           Après 2006         Nul          60
141137              33063           Après 2006        Fort         499
141138              33063           Après 2006       Moyen         867
141139              33063           Avant 1915       Moyen       10246
141140              33063           Avant 1915        Fort        6639
141141              33063           Avant 1915         Nul          37
141142              33063             Inconnue       Moyen          48
141143              33063             Inconnue         Nul           1

# GASPAR & CATNAT

In [73]:
catnat = pd.read_csv('../csv/gaspar/catnat_gaspar.csv', delimiter=';', dtype={"cod_commune": str})
catnat.head()

,cod_nat_catnat,cod_commune,lib_commune,num_risque_jo,lib_risque_jo,dat_deb,dat_fin,dat_pub_arrete,dat_pub_jo,dat_maj
0,BUDD8750027A,06120,Saint-Étienne-de-Tinée,GLT,Glissement de Terrain,1985-01-01,1986-12-31,1987-05-20,1987-05-24,2022-05-20 15:53:47.090
1,BUDD8750038A,2B050,Calvi,ICB,Inondations et/ou Coulées de Boue,1987-01-14,1987-01-15,1987-06-24,1987-07-10,2022-05-20 15:53:47.111
2,BUDD8750038A,30006,Aimargues,ICB,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20 15:53:47.138
3,BUDD8750038A,30020,Aubord,ICB,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20 15:53:47.138
4,BUDD8750038A,30033,Beauvoisin,ICB,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20 15:53:47.138

In [49]:
catnat.lib_risque_jo.unique()

array(['Glissement de Terrain', 'Inondations et/ou Coulées de Boue',
       'Mouvement de Terrain', 'Avalanche', 'Secousse Sismique',
       'Inondations Remontée Nappe',
       "Chocs Mécaniques liés à l'action des Vagues",
       'Effondrement et/ou Affaisement',
       'Eboulement et/ou Chute de Blocs', 'Sécheresse',
       'Vents Cycloniques', 'Raz de Marée', 'Lave Torrentielle',
       'Tempête', 'Poids de la Neige',
       'Glissement et Effondrement de Terrain',
       'Glissement et Eboulement Rocheux', 'Coulée de Boue', 'Divers',
       'Eruption Volcanique', 'Grêle'], dtype=object)

In [50]:
catnat[catnat.lib_risque_jo == 'Sécheresse'].head(10)

,cod_nat_catnat,cod_commune,lib_commune,num_risque_jo,lib_risque_jo,dat_deb,dat_fin,dat_pub_arrete,dat_pub_jo,dat_maj
5490,INTE0000771A,04001,Aiglun,SEC,Sécheresse,1998-01-01,1999-09-30,2000-12-27,2000-12-29,2022-05-24 11:24:18.263
5491,INTE0000771A,04047,Champtercier,SEC,Sécheresse,1997-04-01,1998-06-30,2000-12-27,2000-12-29,2022-05-24 11:24:17.118
5492,INTE0000771A,04128,Montfuron,SEC,Sécheresse,1997-04-01,1999-07-31,2000-12-27,2000-12-29,2022-05-24 11:24:17.120
5493,INTE0000771A,09061,Les Bordes-sur-Arize,SEC,Sécheresse,1989-05-01,1990-12-31,2000-12-27,2000-12-29,2022-05-24 11:24:18.265
5494,INTE0000771A,09307,Taurignan-Castet,SEC,Sécheresse,1989-05-01,1990-12-31,2000-12-27,2000-12-29,2022-05-24 11:24:18.265
5495,INTE0000771A,11025,Bagnoles,SEC,Sécheresse,1995-01-01,1995-12-31,2000-12-27,2000-12-29,2022-05-24 11:24:17.168
5496,INTE0000771A,11025,Bagnoles,SEC,Sécheresse,1995-01-01,1995-12-31,2000-12-27,2000-12-29,2022-05-24 11:24:17.168
5497,INTE0000771A,11025,Bagnoles,SEC,Sécheresse,1998-02-01,1998-09-30,2000-12-27,2000-12-29,2022-05-24 11:24:17.170
5498,INTE0000771A,11025,Bagnoles,SEC,Sécheresse,1998-02-01,1998-09-30,2000-12-27,2000-12-29,2022-05-24 11:24:17.170
5499,INTE0000771A,11069,Carcassonne,SEC,Sécheresse,1998-02-01,1998-09-30,2000-12-27,2000-12-29,2022-05-24 11:24:17.170

# Recherche corrélation CATANAT & Batiments

Hypothèse: plus une commune a des maisons exposées à un risque fort (RGA élevé, % maisons construites > 1945) plus il y a des CATNAT de type Sécheresse enregistrés par la commune

In [74]:
sec = catnat[catnat.num_risque_jo == 'SEC']

In [82]:
sec_agg = sec.groupby('cod_commune').size().to_frame('count_sec').reset_index(names='code_commune_insee')
sec_agg.head()

  code_commune_insee  count_sec
0              01004          5
1              01007          5
2              01012          2
3              01013          1
4              01014          2

In [77]:
sec_agg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14229 entries, 0 to 14228
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   code_commune_insee  14229 non-null  object
 1   count               14229 non-null  int64
dtypes: int64(1), object(1)
memory usage: 222.5+ KB

In [83]:
df = df_agg.merge(sec_agg, how='left', on='code_commune_insee')

In [84]:
df.head()

  code_commune_insee periode_construction alea_argile  nb_maisons  count_sec
0              01001            1916-1945      Faible           5        NaN
1              01001            1946-1970      Faible           4        NaN
2              01001            1971-1990      Faible          93        NaN
3              01001            1991-2005       Moyen           1        NaN
4              01001            1991-2005      Faible          78        NaN

In [85]:
df[~df.count_sec.isna()].head()

   code_commune_insee periode_construction alea_argile  nb_maisons  count_sec
22              01004            1916-1945      Faible         191        5.0
23              01004            1916-1945       Moyen          49        5.0
24              01004            1946-1970         Nul           1        5.0
25              01004            1946-1970       Moyen          99        5.0
26              01004            1946-1970      Faible         262        5.0

In [93]:
df.periode_construction.unique()

array(['1916-1945', '1946-1970', '1971-1990', '1991-2005', 'Après 2006',
       'Avant 1915', 'Inconnue'], dtype=object)

In [105]:
df_flat = pd.get_dummies(data=df_agg.head(20), columns=['alea_argile'], prefix='rga')
rga_cols = df_flat.columns[df_flat.columns.str.startswith('rga_')]
df_flat[rga_cols] = df_flat[rga_cols].multiply(df_flat['nb_maisons'], axis=0)
df_flat['constr_avant_1945'] = df_flat['periode_construction'].isin(['Avant 1915', '1916-1945', 'Inconnue'])
df_flat = df_flat.groupby(by=['code_commune_insee','constr_avant_1945']).sum().reset_index().drop(columns=['periode_construction'])
df_flat.head()

,code_commune_insee,constr_avant_1945,nb_maisons,rga_Faible,rga_Moyen,rga_Nul,rga_Fort
0,01001,False,228,224,3,1,0
1,01001,True,130,123,7,0,0
2,01002,False,45,3,38,4,0
3,01002,True,4,0,4,0,0

In [ ]:
df_scored =