In [1]:
%pip install pyarrow

Requirement already satisfied: pyarrow in /home/laurent/projects/14_PrixChangementClimatique/.venv/lib/python3.12/site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
pd.set_option("display.max_columns", None)  # show all cols
pd.set_option("display.max_colwidth", None)  # show full width of showing cols
pd.set_option(
    "display.expand_frame_repr", False
)  # print cols side by side as it's supposed to be

In [4]:
df = pd.read_parquet("ofgl.parquet", engine ="auto")
df.columns

Index(['exer', 'outre_mer', 'reg_code', 'reg_name', 'dep_code', 'dep_name',
       'epci_code', 'epci_name', 'tranche_population', 'rural', 'montagne',
       'touristique', 'tranche_revenu_imposable_par_habitant', 'qpv',
       'com_code', 'com_name', 'categ', 'siren', 'insee', 'lbudg', 'agregat',
       'montant_bp', 'montant_ba', 'montant_flux', 'montant',
       'montant_en_millions', 'ptot', 'euros_par_habitant', 'presence_budget',
       'ordre_analyse1_section1', 'ordre_analyse1_section2',
       'ordre_analyse1_section3', 'ordre_analyse2_section1',
       'ordre_analyse2_section2', 'ordre_analyse2_section3',
       'ordre_analyse3_section1', 'ordre_analyse3_section2',
       'ordre_analyse3_section3', 'ordre_analyse4_section1', 'annee_join',
       'ptot_n'],
      dtype='object')

In [5]:
df["agregat"].unique()

array(['Achats et charges externes', 'Autres dotations de fonctionnement',
       "Concours de l'Etat", 'Dépenses de fonctionnement',
       "Dépenses d'équipement", "Dépenses d'intervention",
       "Dépenses d'investissement hors remb", 'Dépôts au Trésor', 'DETR',
       'Dotation globale de fonctionnement', 'Emprunts hors GAD',
       "Remboursements d'emprunts hors GAD", 'Annuité de la dette',
       "Dépenses d'investissement", 'Dépenses totales', 'Epargne nette',
       'Flux net de dette', 'Encours de dette',
       'Encours de dette - Dépôts et cautionnements reçus',
       'Encours de dette - Dettes bancaires et assimilées',
       'Epargne de gestion', 'FCTVA', 'Fiscalité reversée',
       'Fonds de soutien aux emprunts à risque', 'Frais de personnel',
       "Frais d'hébergement", 'Impôts locaux',
       'Dépenses totales hors remb', 'Epargne brute', 'Impôts et taxes',
       'Recettes totales hors emprunts',
       'Capacité ou besoin de financement',
       'Variation du fonds de roulement',
       'Autres dotations et subventions', 'Autres impôts et taxes',
       'Charges financières', 'Péréquations et compensations fiscales',
       "Produit des cessions d'immobilisations",
       'Recettes de fonctionnement', "Recettes d'investissement",
       'Recettes totales', 'Ventes de biens et services',
       'Versement transport', 'Fonds de roulement',
       'Subventions reçues et participations',
       "Taxe d'enlévement des ordures ménagères", 'TVA',
       'Autres dépenses de fonctionnement', 'Crédits de trésorerie',
       'Autres recettes de fonctionnement',
       "Autres dépenses d'investissement",
       "Autres recettes d'investissement",
       "Recettes d'investissement hors emprunts",
       'Subventions aux personnes de droit privé',
       "Subventions d'équipement versées"], dtype=object)

In [6]:
impots_locaux = df[df["agregat"] == "Impôts locaux"]
impots_locaux.head()

              exer outre_mer reg_code              reg_name dep_code dep_name  epci_code                                                epci_name tranche_population rural montagne touristique tranche_revenu_imposable_par_habitant  qpv com_code              com_name    categ      siren  insee                 lbudg        agregat  montant_bp  montant_ba  montant_flux    montant  montant_en_millions    ptot  euros_par_habitant presence_budget ordre_analyse1_section1 ordre_analyse1_section2 ordre_analyse1_section3 ordre_analyse2_section1 ordre_analyse2_section2 ordre_analyse2_section3 ordre_analyse3_section1 ordre_analyse3_section2 ordre_analyse3_section3 ordre_analyse4_section1 annee_join  ptot_n
692633  2019-01-01       Non       84  Auvergne-Rhône-Alpes       01      Ain  200042935    Communauté d'agglomération Haut - Bugey Agglomération                  3   Oui      Oui         Non                                     2  Non    01204  Le Poizat-Lalleyriat  Commune  200053395  01204  LE POIZAT-LALLEYRIAT  Impôts locaux   278407.75         0.0           0.0  278407.75             0.278408   728.0          382.428228               1                    None                    None                    None                    None                    None                    None                    None                    None                    None                    None       2019   762.0
692634  2019-01-01       Non       84  Auvergne-Rhône-Alpes       01      Ain  200040350                         Communauté de communes Bugey Sud                  3   Oui      Oui         Non                                     2  Non    01015       Arboys en Bugey  Commune  200053668  01015       ARBOYS EN BUGEY  Impôts locaux   193339.41         0.0           0.0  193339.41             0.193339   656.0          294.724710               1                    None                    None                    None                    None                    None                    None                    None                    None                    None                    None       2019   682.0
692635  2019-01-01       Non       84  Auvergne-Rhône-Alpes       01      Ain  200040350                         Communauté de communes Bugey Sud                  3   Oui      Oui         Non                                     2  Non    01187         Haut Valromey  Commune  200053676  01187         HAUT VALROMEY  Impôts locaux   312033.66         0.0           0.0  312033.66             0.312034   727.0          429.207235               1                    None                    None                    None                    None                    None                    None                    None                    None                    None                    None       2019   627.0
692636  2019-01-01       Non       84  Auvergne-Rhône-Alpes       01      Ain  200042935    Communauté d'agglomération Haut - Bugey Agglomération                  3   Oui      Oui         Non                                     2  Non    01080    Champdor-Corcelles  Commune  200056695  01080    CHAMPDOR-CORCELLES  Impôts locaux   199299.00         0.0           0.0  199299.00             0.199299   672.0          296.575893               1                    None                    None                    None                    None                    None                    None                    None                    None                    None                    None       2019   660.0
692637  2019-01-01       Non       84  Auvergne-Rhône-Alpes       01      Ain  200071751  Communauté d'agglomération du Bassin de Bourg-en-Bresse                  4   Oui      Non         Non                                     2  Non    01426         Val-Revermont  Commune  200057347  01426         VAL REVERMONT  Impôts locaux   966882.31         0.0           0.0  966882.31             0.966882  2636.0          366.799055               1                    None                    None                    None                    None                    None                    None                    None                    None                    None                    None       2019  2552.0

In [7]:
verif = impots_locaux[impots_locaux["com_code"] == "01263"]
verif = verif.sort_values("exer", ascending = False)
verif.head(1)

                exer outre_mer reg_code              reg_name dep_code dep_name  epci_code                                   epci_name tranche_population rural montagne touristique tranche_revenu_imposable_par_habitant  qpv com_code             com_name    categ      siren  insee                lbudg        agregat  montant_bp  montant_ba  montant_flux    montant  montant_en_millions    ptot  euros_par_habitant presence_budget ordre_analyse1_section1 ordre_analyse1_section2 ordre_analyse1_section3 ordre_analyse2_section1 ordre_analyse2_section2 ordre_analyse2_section3 ordre_analyse3_section1 ordre_analyse3_section2 ordre_analyse3_section3 ordre_analyse4_section1 annee_join  ptot_n
12151005  2024-01-01       Non       84  Auvergne-Rhône-Alpes       01      Ain  200070118  Communauté de communes Val de Saône Centre                  5   Non      Non         Non                                     2  Non    01263  Montmerle-sur-Saône  Commune  210102638  01263  MONTMERLE-SUR-SAONE  Impôts locaux   2203352.0         0.0           0.0  2203352.0             2.203352  3882.0          567.581659               1                    None                    None                    None                    None                    None                    None                    None                    None                    None                    None       2024  3882.0

In [8]:
impots_locaux["exer"].value_counts()

exer
2017-01-01    35410
2018-01-01    35353
2020-01-01    34967
2019-01-01    34966
2021-01-01    34964
2022-01-01    34951
2023-01-01    34940
2024-01-01    34931
Name: count, dtype: int64

In [9]:
impots_locaux["annee"] = impots_locaux["exer"].astype(str).str[:4].astype(int)
impots_locaux["annee"].value_counts()

/tmp/ipykernel_6609/4081583437.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  impots_locaux["annee"] = impots_locaux["exer"].astype(str).str[:4].astype(int)

annee
2017    35410
2018    35353
2020    34967
2019    34966
2021    34964
2022    34951
2023    34940
2024    34931
Name: count, dtype: int64

In [10]:
impots_locaux = impots_locaux[["annee", "com_code", "com_name", "agregat", "montant", "ptot", "euros_par_habitant"]]
impots_locaux.head()

        annee com_code              com_name        agregat    montant    ptot  euros_par_habitant
692633   2019    01204  Le Poizat-Lalleyriat  Impôts locaux  278407.75   728.0          382.428228
692634   2019    01015       Arboys en Bugey  Impôts locaux  193339.41   656.0          294.724710
692635   2019    01187         Haut Valromey  Impôts locaux  312033.66   727.0          429.207235
692636   2019    01080    Champdor-Corcelles  Impôts locaux  199299.00   672.0          296.575893
692637   2019    01426         Val-Revermont  Impôts locaux  966882.31  2636.0          366.799055

In [11]:
impots_locaux = impots_locaux.rename(columns = {
    "com_code" : "code_geo"
})
impots_locaux.head(2)

        annee code_geo              com_name        agregat    montant   ptot  euros_par_habitant
692633   2019    01204  Le Poizat-Lalleyriat  Impôts locaux  278407.75  728.0          382.428228
692634   2019    01015       Arboys en Bugey  Impôts locaux  193339.41  656.0          294.724710

In [13]:
#export en CSV
impots_locaux.to_csv("ofgl_impots_locaux.csv", index=False)