In [1]:
cd ../../

/Users/chloe/Documents/GitHub/14_PrixChangementClimatique

In [171]:
cd ~/Documents/GitHub/14_PrixChangementClimatique

/Users/chloe/Documents/GitHub/14_PrixChangementClimatique

In [5]:
ls

LICENSE         d4g-utils/      logs/           tox.ini         website/
README.md       data/           pyproject.toml  uv.lock

In [2]:
cd ../../

/Users/chloe/Documents/GitHub/14_PrixChangementClimatique

In [21]:
import duckdb

con = duckdb.connect("data/dbt_pipeline/dev.duckdb")

In [22]:
rga = con.sql("SELECT * FROM rga").df()

In [24]:
rga.columns

Index(['gid', 'niveau', 'surf_m2', 'geom', 'code_departement'], dtype='str')

In [ ]:
con = duckdb.connect("data/dbt_pipeline/dev.duckdb")
df_prime_assurances = con.sql("SELECT * FROM rga").df()

IOException: IO Error: Could not set lock on file "/Users/chloe/Documents/GitHub/14_PrixChangementClimatique/data/dbt_pipeline/dev.duckdb": Conflicting lock is held in /opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python (PID 85307) by user chloe. However, you would be able to open this database in read-only mode, e.g. by using the -readonly parameter in the CLI. See also https://duckdb.org/docs/stable/connect/concurrency

In [178]:
budget_per_compte_communes = con.sql("SELECT * FROM budget_per_compte_communes")

In [5]:
import pandas as pd

In [9]:
df = pd.read_csv('data/dbt_pipeline/pipeline_inputs/impots_REI_2022.csv',low_memory=False)

In [20]:
len(df.columns)

1180

FB - TSE / BASE NETTE
FB - TSE / TAUX NET
FB - TSE / MONTANT REEL
FB - TSE / NOMBRE D'ARTICLES
FB - TSE / MONTANT LISSAGE
FB - TSE AUTRES / BASE NETTE
FB - TSE AUTRES / TAUX NET
FB - TSE AUTRES / MONTANT REEL NET
FB - TSE AUTRES / NOMBRE D'ARTICLES
FB - TSE AUTRES / MONTANT LISSAGE
FB - GEMAPI / BASE NETTE INTERCOMMUNALITE
FB - GEMAPI / TAUX NET INTERCOMMUNALITE
FB - GEMAPI / MONTANT REEL INTERCOMMUNALITE
FB - GEMAPI / NOMBRE D'ARTICLES INTERCOMMUNALITE
FB - GEMAPI / MONTANT LISSAGE INTERCOMMUNALITE
FB - TASA / BASE NETTE
FB - TASA / TAUX NET
FB - TASA / MONTANT REEL
FB - TASA / NOMBRE D'ARTICLES
FB - TASA / MONTANT DU LISSAGE
FB - TAXE D'ENLEVEMENT O.M. /  NOMBRE D'ARTICLES
FB - TAXE D'ENLEVEMENT O.M. /  MONTANT LISSAGE
FB - TAXE D'ENLEVEMENT O.M. /  TAUX PLEIN - BASE NETTE
FB - TAXE D'ENLEVEMENT O.M. /  TAUX PLEIN - TAUX NET
FB - TAXE D'ENLEVEMENT O.M. /  TAUX PLEIN - MONTANT NET LISSE
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT A - BASE NETTE
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT A - TAUX NET
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT A - MONTANT NET
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT B - BASE NETTE
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT B - TAUX NET
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT B - MONTANT NET
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT C - BASE NETTE
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT C - TAUX NET
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT C -  MONTANT NET
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT D - BASE NETTE
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT D - TAUX NET
FB - TAXE D'ENLEVEMENT D'O.M. /  TAUX REDUIT D - MONTANT NET
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT E - BASE NETTE
FB - TAXE D'ENLEVEMENT O.M. /  TAUX REDUIT E - TAUX NET
FB - TAXE D'ENLEVEMENT D'O.M. /  TAUX REDUIT E - MONTANT NET
FB - TAXE D'ENLEVEMENT D'O.M. /  TOTAL - MONTANT REEL
FB - TAXE INCITATIVE ENLEVEMENT DES ORDURES MENAGERES / MONTANT REEL / COMMUNE
FB - TAXE INCITATIVE ENLEVEMENT DES ORDURES MENAGERES / MONTANT REEL / SYNDICAT
FB - TAXE INCITATIVE ENLEVEMENT DES ORDURES MENAGERES / MONTANT REEL / GFP
FB - NIVEAU DE COLLECTIVITE PERCEVANT LA TEOM   COM:1, SYN:2 , GFP:3
Bénéficiaire de la TEOM (C, I, P ou S)
FB - BASE DES LOCAUX D'HABITATION EXONEREE POUR 2 ANS / COMMUNE
FB - BASE DES LOCAUX D' HABITATION EXONERES POUR 2 ANS / INTERCOMMUNALITE
FB - BASE DES LOCAUX AUTRES QUE D'HABITATION EXONERES 2 ANS / COMMUNE
FB - BASE DES LOCAUX AUTRES QUE D'HABITATION EXONERES 2 ANS / INTERCOMMUNALITE
FB - BASE DES LOCAUX SITUES DANS LES QUARTIERS PRIORITAIRES DE LA VILLE (QV) EXONERES 5 ANS / COMMUNE
FB - BASE DES LOCAUX SITUES DANS LES QUARTIERS PRIORITAIRES DE LA VILLE (QV) EXONERES 5 ANS / INTERCOMMUNALITE
FB - BASE DES LOCAUX FAISANT OBJET BAIL A REHABILITATION (RC) EXONERES POUR LA DUREE DU BAIL / COMMUNE
FB - BASE DES LOCAUX FAISANT OBJET BAIL A REHABILITATION (RC) EXONERES POUR LA DUREE DU BAIL / INTERCOMMUNALITE
FB - BASES EXONEREES NON COMPENSES LOCAUX NAH (HORS AP, DF et RI) / COMMUNE
FB - BASES EXONEREES NON COMPENSES LOCAUX NAH (HORS AP, DF et RI) / GFP
FB - BASES EXONEREES NON COMPENSEES LOCAUX NAH : ANTI POLLUTION (AP), DESHYDRATATION FOURRAGES (DF) ET RECHERCHE INDUSTRIELLE (RI) / COMMUNE
FB - BASES EXONEREES NON COMPENSEES LOCAUX NAH : ANTI POLLUTION (AP), DESHYDRATATION FOURRAGES (DF) ET RECHERCHE INDUSTRIELLE (RI) / GFP
FB - BASES EXONEREES NON COMPENSEES LOCAUX D HABITATION / COMMUNE
FB - BASES EXONEREES NON COMPENSEES LOCAUX D HABITATION / INTERCOMMUNALITE
FB - BASES EXONEREES ABATTEMENT 30% LOGEMENTS ANTISISMIQUES DOM (ART 1388 TER) / COMMUNE
FB - BASES EXONEREES ABATTEMENT 30% LOGEMENTS ANTISISMIQUES DOM (ART 1388 TER) / INTERCOMMUNALITE
FB - BASES EXONEREES ABATTEMENT DISPOSITIF LODEOM (ART 1388 QUINQUIES) / COMMUNE
FB - BASES EXONEREES ABATTEMENT DISPOSITIF LODEOM (ART 1388 QUINQUIES) / INTERCOMMUNALITE
FB - BASES EXONEREES IMMEUBLES EN QPV (ART 1383 C TER) / COMMUNE
FB - BASES EXONEREES IMMEUBLES EN QPV (ART 1383 C TER) / INTERCOMMUNALITE
FB - BASES EXONEREES COMPENSEES 60% MAYOTTE (1496 II bis) / COMMUNE
FB - BASES EXONEREES COMPENSEES 60% MAYOTTE (1496 II bis) / GFP
FB - BASES EXONEREES COMPENSEES BUD et ZDP (1383 F-I, 1383 J-I) / COMMUNE
FB - BASES EXONEREES COMPENSEES BUD et ZDP (1383 F-I, 1383 J-I) / GFP
FB - BASES EXONEREES COMPENSEES ABATTEMENTS 50% LOCAUX INDUSTRIELS / COMMUNE
FB - BASES EXONEREES COMPENSEES ABATTEMENTS 50% LOCAUX INDUSTRIELS / GFP
FB - BASES EXONEREES COMPENSEES ZRC (1382 I) / COMMUNE
FB - BASES EXONEREES COMPENSEES ZRC (1382 I)) / GFP
TF - BASES EXONEREES ECF (ANCIENS DO) - MONTANT
TF - BASES EXONEREES ECF (ANCIENS DO) - NOMBRE
TF - BASES EXONEREES DOM (ARTICLE 332 an II) - MONTANT
TF - DEGREVEMENT D'OFFICE  /  COTISATIONS < 12 EUROS - MONTANT
TF - DEGREVEMENT D'OFFICE  /  COTISATIONS < 12 EUROS - NOMBRE
TF - MONTANT DES DO JEUNES AGRICULTEURS (ETAT)
TF - NOMBRE DES DO JEUNES AGRICULTEURS (ETAT)
TF - MONTANT DES DO JEUNES AGRICULTEURS (COLLECTIVITES)
TF - MONTANT DES DO JEUNES AGRICULTEURS - Commune (COLLECTIVITES)
TF - MONTANT DES DO JEUNES AGRICULTEURS - Syndicats (COLLECTIVITES)
TF - MONTANT DES DO JEUNES AGRICULTEURS - EPCI (COLLECTIVITES)
TF - NOMBRE DES DO JEUNES AGRICULTEURS (COLLECTIVITES)
TF-DO CONDITION MODESTE 65-75 ANS/PLAFOND 100 EUROS/MONTANT
TF-DO CONDITION MODESTE 65-75 ANS/PLAFOND 100 EUROS/NB
TF - NOMBRE D'AVIS D'IMPOSITION
TH - FRAIS DE GESTION THP-THE
TH - FRAIS DE GESTION THS
TH - FRAIS DE GESTION THLV
TH - COMMUNE / BASE NETTE
THLV - COMMUNE / VALEUR LOCATIVE BRUTE
TH - COMMUNE / TAUX NET
TH - COMMUNE / MONTANT REEL DONT THP/E AU PROFIT DE L ETAT
TH - COMMUNE / MONTANT REEL COMMUNAL DE THP/E AU PROFIT DE L ETAT
TH - COMMUNE / MONTANT REEL COMMUNAL AU PROFIT DE LA COMMUNE
TH - COMMUNE / MONTANT LISSAGE
TH - COMMUNE / PRODUIT REEL DES LOCAUX VACANTS
TH - COMMUNE / NOMBRE D ARTICLES  AYANT UNE BASE NETTE
THLV - COMMUNE / NOMBRE D ARTICLES AYANT UNE VL BRUTE
TH - SYNDICATS ET ORG. ASSIMILES /  BASE NETTE
THLV - SYNDICATS ET ORG. ASSIMILES /  VALEUR LOCATIVE BRUTE
TH - SYNDICATS ET ORG. ASSIMILES / TAUX NET
TH - SYNDICATS ET ORG. ASSIMILES /  MONTANT REEL
TH - SYNDICATS ET ORG. ASSIMILES /  MONTANT LISSAGE
TH - SYNDICATS ET ORG. ASSIMILES /  PRODUIT REEL DES LOCAUX VACANTS
TH - INTERCOMMUNALITE / BASE NETTE
TH - INTERCOMMUNALITE / BASE BRUTE & NETTE DES LOCAUX VACANTS
TH - INTERCOMMUNALITE / TAUX APPLICABLE SUR LE TERRITOIRE DE LA COMMUNE
TH - INTERCOMMUNALITE / TAUX VOTE
TH - INTERCOMMUNALITE / MONTANT REEL DONT THP/E AU PROFIT DE L ETAT
TH - INTERCOMMUNALITE / MONTANT REEL INTERCOMMUNALITE DE THP/E AU PROFIT DE L ETAT
TH - INTERCOMMUNALITE / MONTANT REEL INTERCOMMUNALITE AU PROFIT DU GROUPEMENT
TH - INTERCOMMUNALITE / MONTANT LISSAGE
TH - INTERCOMMUNALITE / MONTANT REEL NET DES LOCAUX VACANTS
TH - INTERCOMMUNALITE / NOMBRE D ARTICLES AYANT UNE BASE NETTE
THLV - INTERCOMMUNALITE / NOMBRE D ARTICLES AYANT UNE BASE BRUTE & NETTE
TH - TSE / BASE NETTE
TH - TSE / TAUX NET
TH - TSE / MONTANT REEL
TH - TSE / MONTANT LISSAGE
TH - TSE / NOMBRE D ARTICLES
TH - TSE GRAND PARIS OU EPFL GUADELOUPE OU EPFL MARTINIQUE / BASE NETTE
TH - TSE GRAND PARIS OU EPFL GUADELOUPE OU EPFL MARTINIQUE / TAUX NET
TH - TSE GRAND PARIS OU EPFL GUADELOUPE OU EPFL MARTINIQUE / MONTANT REEL
TH - TSE GRAND PARIS OU EPFL GUADELOUPE OU EPFL MARTINIQUE / LISSAGE
TH - TSE GRAND PARIS OU EPFL GUADELOUPE OU EPFL MARTINIQUE / NOMBRE D ARTICLES
TH - BASE TAXABLE NETTE INTERCOMMUNALE TAXE GEMAPI
TH - TAUX INTERCOMMUNAL TAXE GEMAPI
TH - MONTANT REEL INTERCOMMUNAL TAXE GEMAPI
TH - MONTANT LISSAGE INTERCOMMUNAL TAXE GEMAPI
TH - MONTANT NET INTERCOMMUNAL DES LOGEMENTS VACANTS TAXE GEMAPI
TH - COMMUNE / NOMBRE LISSAGE
TH - SYNDICATS ET ORG. ASSIMILES / NOMBRE LISSAGE
TH - INTERCOMMUNALITE / NOMBRE LISSAGE
TH - TSE / NOMBRE LISSAGE
TH - TSE AUTRES / NOMBRE LISSAGE
TH - GEMAPI / NOMBRE LISSAGE
TH - NOMBRE DE LOCAUX TAXES SUSCEPTIBLES DE MAJORATION DES RESIDENCES SECONDAIRES
TH - VALEUR LOCATIVE DES LOCAUX SUSCEPTIBLES DE MAJORATION DES RESIDENCES SECONDAIRES
TH - TAUX DE MAJORATION DES RESIDENCES SECONDAIRES
TH - MONTANT REEL DE LA MAJORATION DES RESIDENCES SECONDAIRES
TH - NOMBRE D'ARTICLES AYANT UN PRELEVEMENT SUPPLEMENTAIRE SUR LES RESIDENCES SECONDAIRES
TH - V.L. BRUTE DE THP/THE
TH - V.L. BRUTE  DES LOCAUX DE LA COMMUNE (ENSEMBLE DES LOCAUX)
TH - NB ARTICLES AYANT V.L. BRUTE (ENSEMBLE DE LOCAUX)
TH - V.L. BRUTE (LOCAUX SOUMIS A LA MAJORATION THS)
TH - NOMBRE DE LOCAUX TAXES DE THP (ENSEMBLE DES LOCAUX)
TH - NOMBRE DE LOCAUX TAXES DE THE (ENSEMBLE DES LOCAUX)
TH - NOMBRE DE LOCAUX TAXES DE THS (ENSEMBLE DES LOCAUX)
TH - NOMBRE DE LOCAUX TAXES (LOCAUX SOUMIS MAJO THS)
TH - NOMBRE DE LOCAUX TAXES DE THP (AUTRES LOCAUX ET DEPENDANCES BATIES)
TH - NOMBRE DE LOCAUX TAXES DE THE (AUTRES LOCAUX ET DEPENDANCES BATIES)
TH - NOMBRE DE LOCAUX TAXES DE THS (AUTRES LOCAUX ET DEPENDANCES BATIES)
TH - NOMBRE DE LOGEMENTS VACANTS IMPOSES À LA THLV (SUR DELIBERATION DE LA COMMUNE)
TH - NOMBRE DE LOGEMENTS VACANTS IMPOSES À LA THLV (SUR DELIBERATION DE L'EPCI)
TH - V.L. MOYENNE UTILISEE POUR LE CALCUL DES ABATTEMENTS / COMMUNE
TH - V.L. MOYENNE UTILISEE POUR LE CALCUL DES ABATTEMENTS / SYNDICATS
TH - V.L. MOYENNE UTILISEE POUR LE CALCUL DES ABATTEMENTS / INTERCOMMUNALITE
TH - QUOTITE DES ABATTEMENTS AVANT AJUSTEMENT/ 1ERE ET 2EME PERSONNE A CHARGE  - COMMUNE
TH - QUOTITE DES ABATTEMENTS AVANT AJUSTEMENT / 1ERE ET 2EME PERSONNE A CHARGE - INTERCOMMUNALITE
TH - QUOTITE DES ABATTEMENTS  AJUSTEE/ 1ERE ET 2EME PERSONNE A CHARGE  - COMMUNE
TH - QUOTITE DES ABATTEMENTS AJUSTEE / 1ERE ET 2EME PERSONNE A CHARGE - INTERCOMMUNALITE
TH - QUOTITE DES ABATTEMENTS AVANT AJUSTEMENT / A PARTIR DE LA 3EME PERSONNE A CHARGE - COMMUNE
TH - QUOTITE DES ABATTEMENTS AVANT AJUSTEMENT / A PARTIR DE LA 3EME PERSONNE A CHARGE - INTERCOMMUNALITE
TH - QUOTITE DES ABATTEMENTS AJUSTEE / A PARTIR DE LA 3EME PERSONNE A CHARGE - COMMUNE
TH - QUOTITE DES ABATTEMENTS AJUSTEE / A PARTIR DE LA 3EME PERSONNE A CHARGE - INTERCOMMUNALITE
TH - QUOTITE DES ABATTEMENTS AVANT AJUSTEMENT/ ABATTEMENT GENERAL A LA BASE - COMMUNE
TH - QUOTITE DES ABATTEMENTS AVANT AJUSTEMENT/ ABATTEMENT GENERAL A LA BASE - INTERCOMMUNALITE
TH - QUOTITE DES ABATTEMENTS AJUSTEE / ABATTEMENT GENERAL A LA BASE - COMMUNE
TH - QUOTITE DES ABATTEMENTS AJUSTEE / ABATTEMENT GENERAL A LA BASE - INTERCOMMUNALITE
TH - QUOTITE DES ABATTEMENTS AVANT AJUSTEMENT / ABATTEMENT SPECIAL A LA BASE NI.IR - COMMUNE
TH - QUOTITE DES ABATTEMENTS AVANT AJUSTEMENT / ABATTEMENT SPECIAL A LA BASE NI.IR - INTERCOMMUNALITE
TH - QUOTITE DES ABATTEMENTS AJUSTEE / ABATTEMENT SPECIAL A LA BASE NI.IR - COMMUNE
TH - QUOTITE DES ABATTEMENTS AJUSTEE / ABATTEMENT SPECIAL A LA BASE NI.IR - INTERCOMMUNALITE
TH - QUOTITE DES ABATTEMENTS AVANT AJUSTEMENT / ABATTEMENT SPECIAL HANDICAPES A LA BASE - COMMUNE
TH - QUOTITE DES ABATTEMENTS AVANT AJUSTEMENT / ABATTEMENT SPECIAL HANDICAPES A LA BASE - INTERCOMMUNALITE
TH - QUOTITE DES ABATTEMENTS AJUSTEE / ABATTEMENT SPECIAL HANDICAPES A LA BASE - COMMUNE
TH - QUOTITE DES ABATTEMENTS AJUSTEE / ABATTEMENT SPECIAL HANDICAPES A LA BASE - INTERCOMMUNALITE
TH - NOMBRE DE PERSONNES A CHARGE / TOTAL
TH - NOMBRE TOTAL DE PERSONNES A CHARGE (BENEFICIANT D UN ABATTEMENT)
TH - V.L. NETTES DES RESIDENCES SECONDAIRES ET DEPENDANCES NON RATTACHEES
TH - NOMBRE DE RESIDENCES SECONDAIRES ET DEPENDANCES NON RATTACHEES
TH-V.L. BRUTE DES MAISONS EXCEPTIONNELLES
TH - NOMBRE DE MAISONS EXCEPTIONNELLES
TH - NOMBRE D'ARTICLES PASSIBLES DES FRAIS DE 3%
TH - NOMBRE D'ARTICLES PASSIBLES DES FRAIS 8% (LOCAUX VACANTS)
TH - NOMBRE D ARTICLES PASSIBLES DES FRAIS DE 1%
TH - BASES BRUTES EXONEREES (ANCIENS DO TOTAUX) - MONTANT
TH - BASES BRUTES EXONEREES (ANCIENS DO TOTAUX) - NOMBRE
TH - BASES NETTES COMMUNALES EXONEREES (ANCIENS DO TOTAUX) - MONTANT
TH - BASES NETTES INTERCOMMUNALES EXONEREES (ANCIENS DO TOTAUX) - MONTANT
TH - BASES BRUTES EXONEREES SORTIE PROGRESSIVE - NOMBRE
TH - ABATTEMENTS MAYOTTE - MONTANT
TH - ABATTEMENTS MAYOTTE - NOMBRE DE BENEFICIAIRES
TH - BASES BRUTES EXONEREES DES LOCAUX EN ZRR (MEUBLES DE TOURISME)
TH - BASES BRUTES EXONEREES DES LOCAUX EN ZRR (CHAMBRES D HOTES)
TH - BASE EXONEREE TSE / MONTANT
TH - BASE EXONEREE TSE / NOMBRE
TH - BASES NETTES INTERCOMMUNALES EXONEREES DE TAXE GEMAPI
TH - DEGREVEMENTS GESTIONNAIRES DE FOYERS - MONTANT
TH - DEGREVEMENTS GESTIONNAIRES DE FOYERS - NOMBRE
TH - EXONERATION TOTALE REFORME TH - MONTANT
TH - REFORME TH TOTALE - NOMBRE
TH - EXONERATION REFORME TH AVEC LISSAGE - MONTANT
TH - NON-VALEURS REFORME TH  AVEC LISSAGE - MONTANT
TH - REFORME TH  AVEC LISSAGE - NOMBRE
TH - EXONERATION REFORME TH FORFAITAIRE - MONTANT
TH - NON-VALEURS REFORME TH FORFAITAIRE - MONTANT
TH - REFORME TH FORFAITAIRE - NOMBRE
TH - COTISATIONS < 12 EUROS (HORS REFORME TH)- MONTANT
TH - COTISATIONS < 12 EUROS (HORS REFORME TH) - NOMBRE
TH - COTISATIONS < 12 EUROS (TOTAL DONT REFORME TH) - MONTANT
TH -VALEUR LOCATIVE BRUTE EXONERATION SPECIFIQUE DOM
TH - NOMBRE D ARTICLES EXONERATION SPECIFIQUE DOM
TH - DEGREVEMENTS TOTAUX, DONT EXONERATIONS REFORME TH - MONTANT
TH - DEGREVEMENTS TOTAUX, DONT EXONERATIONS REFORME TH - NOMBRE
TH - NON-VALEURS HORS REFORME TH - MONTANT
TH - NON-VALEURS HORS REFORME TH - NOMBRE
TH - NOMBRE D AVIS D IMPOSITION DE TH
TH - VL brute des locaux (hors résidences secondaires et dépendances)(Montant)
TH - VL brute des locaux (hors résidences secondaires et dépendances) (Nombre)
TH - VL des résidences secondaires (Montant)
TH - BASE NETTE IMPOSEE OU DEGREVEE RESIDENCES PRINC ET DEP BATIES RATTACHEES - COMMUNE
TH - BASE NETTE IMPOSEE OU DEGREVEE RESIDENCES PRINC ET DEP BATIES RATTACHEES - INTERCOMMUNALITE
BASE NETTE IMPOSEE OU DEGREVEE RESIDENCES SECONDAIRES - COMMUNE
BASE NETTE IMPOSEE OU DEGREVEE RESIDENCES SECONDAIRES - INTERCOMMUNALITE
TH - Nombre d'articles imposés afférents aux résidences secondaires
TH - PERSONNES A CHARGE DE RANG 1 ET 2 - TOTAL DES ABATTEMENTS (COMMUNE)
TH - PERSONNES A CHARGE A PARTIR DE LA 3EME - TOTAL DES ABATTEMENTS (COMMUNE)
TH - PERSONNES A CHARGE DE RANG 1 ET 2 - TOTAL DES ABATTEMENTS (SYNDICATS)
TH - PERSONNES A CHARGE DE RANG 1 ET 2 - TOTAL DES ABATTEMENTS (GEMAPI)
TH - PERSONNES A CHARGE A PARTIR DE LA 3EME - TOTAL DES ABATTEMENT (SYNDICATS)
TH - PERSONNES A CHARGE A PARTIR DE LA 3EME - TOTAL DES ABATTEMENT (GEMAPI)
TH - ABATTEMENT GENERAL A LA BASE - TOTAL DES ABATTEMENTS (COMMUNE)
TH - ABATTEMENT GENERAL A LA BASE - TOTAL DES ABATTEMENTS (SYNDICATS)
TH - ABATTEMENT GENERAL A LA BASE - TOTAL DES ABATTEMENTS (GEMAPI)
TH - ABATTEMENT SPECIAL A LA BASE - TOTAL DES ABATTEMENTS (COMMUNE)
TH - ABATTEMENT SPECIAL A LA BASE - TOTAL DES ABATTEMENTS (SYNDICATS)
TH - ABATTEMENT SPECIAL A LA BASE - TOTAL DES ABATTEMENTS (GEMAPI)
TH - ABATTEMENT SPECIAL HANDICAPES A LA BASE - TOTAL DES ABATTEMENTS (COMMUNE)
TH - ABATTEMENT SPECIAL HANDICAPES A LA BASE - TOTAL DES ABATTEMENTS (SYNDICATS)
TH - ABATTEMENT SPECIAL HANDICAPES A LA BASE - TOTAL DES ABATTEMENTS (GEMAPI)
TH - PERSONNES A CHARGE DE RANG 1 ET 2 - TOTAL DES ABATTEMENTS (INTERCOMMUNALITE)
TH - PERSONNES A CHARGE A PARTIR DE LA 3EME - TOTAL DES ABATTEMENTS (INTERCOMMUNALITE)
TH - ABATTEMENT GENERAL A LA BASE - TOTAL DES ABATTEMENTS (INTERCOMMUNALITE)
TH - ABATTEMENT SPECIAL A LA BASE - TOTAL DES ABATTEMENTS (INTERCOMMUNALITE)
TH - ABATTEMENT SPECIAL HANDICAPES A LA BASE - TOTAL DES ABATTEMENTS (INTERCOMMUNALITE)
CFE - COMMUNE / BASE
CFE - COMMUNE /TAUX NET
CFE - COMMUNE / PRODUIT REEL NET
CFE - COMMUNE / NOMBRE ARTICLES COMPORTANT UNE BASE TAXABLE DE CFE
CFE - SYNDICATS ET ORG. ASSIMILES / BASES
CFE - SYNDICATS ET ORG. ASSIMILES /  TAUX NET
CFE - SYNDICATS ET ORG. ASSIMILES /  PRODUIT REEL NET
CFE - SYNDICATS ET ORG. ASSIMILES /  NOMBRE ARTICLES
CFE - INTERCOMMUNALITE / BASE / FISCALITE ADDITIONNELLE OU FP DE ZONE (HORS ZONE)
CFE - INTERCOMMUNALITE / TAUX NET / FISCALITE ADDITIONNELLE OU FP DE ZONE (HORS ZONE)
CFE - INTERCOMMUNALITE / TAUX VOTE / FISCALITE ADDITIONNELLE OU FP DE ZONE (HORS ZONE)
CFE - INTERCOMMUNALITE / PRODUIT REEL NET / FISCALITE ADDITIONNELLE OU FP DE ZONE (HORS ZONE)
CFE - INTERCOMMUNALITE /NB ARTICLES / FISCALITE ADDITIONNELLE OU FP DE ZONE (HORS ZONE)
CFE - INTERCOMMUNALITE / BASE / FP UNIQUE OU EN ZAE
CFE - INTERCOMMUNALITE / TAUX NET / FP UNIQUE OU EN ZAE
CFE - INTERCOMMUNALITE / TAUX VOTE / FP UNIQUE OU EN ZAE
CFE - INTERCOMMUNALITE / PRODUIT REEL NET / FP UNIQUE OU EN ZAE
CFE - INTERCOMMUNALITE /NB ARTICLES / FP UNIQUE OU EN ZAE
CFE - INTERCOMMUNALITE / BASE / FP UNIQUE
CFE - INTERCOMMUNALITE / TAUX NET / FP UNIQUE
CFE - INTERCOMMUNALITE / TAUX VOTE / FP UNIQUE
CFE - INTERCOMMUNALITE / PRODUIT REEL NET / FP UNIQUE
CFE - INTERCOMMUNALITE /NB ARTICLES / FP UNIQUE
CFE - INTERCOMMUNALITE / BASE / FPZ EN ZAE
CFE - INTERCOMMUNALITE / TAUX NET / FPZ EN ZAE
CFE - INTERCOMMUNALITE / TAUX VOTE / FPZ EN ZAE
CFE - INTERCOMMUNALITE / PRODUIT REEL NET / FPZ EN ZAE
CFE - INTERCOMMUNALITE /NB ARTICLES / FPZ EN ZAE
CFE - INTERCOMMUNALITE / BASE / FPE EN ZONE EOLIENNE
CFE - INTERCOMMUNALITE / TAUX NET / FPE EN ZONE EOLIENNE
CFE - INTERCOMMUNALITE / TAUX VOTE / FPE EN ZONE EOLIENNE
CFE - INTERCOMMUNALITE / PRODUIT REEL NET / FPE EN ZONE EOLIENNE
CFE - INTERCOMMUNALITE /NB ARTICLES / FPE EN ZONE EOLIENNE
CFE - TSE / BASES
CFE - TSE / TAUX NET
CFE - TSE HORS GRAND PARIS, EPFL Guadeloupe et Martinique  / TAUX VOTE
CFE - TSE GRAND PARIS, EPFL Guadeloupe et Martinique / TAUX VOTE
CFE - TSE / PRODUIT REEL NET
CFE - TSE / NOMBRE ARTICLES
CFE - GEMAPI / BASE INTERCOMMUNALE / FISCALITE ADDITIONNELLE
CFE - GEMAPI / TAUX INTERCOMMUNAL / FISCALITE ADDITIONNELLE
CFE - GEMAPI / PRODUIT REEL NET INTERCOMMUNAL / FISCALITE ADDITIONNELLE
CFE - GEMAPI / NOMBRE ARTICLES INTERCOMMUNAL / FISCALITE ADDITIONNELLE
CFE - GEMAPI / BASE INTERCOMMUNALE / FP UNIQUE OU EN ZAE
CFE - GEMAPI / TAUX INTERCOMMUNAL / FP UNIQUE OU EN ZAE
CFE - GEMAPI / PRODUIT REEL NET INTERCOMMUNAL / FP UNIQUE OU EN ZAE
CFE - GEMAPI / NOMBRE ARTICLES INTERCOMMUNAL / FP UNIQUE OU EN ZAE
CFE - GEMAPI / BASE INTERCOMMUNALE / FP UNIQUE
CFE - GEMAPI / TAUX INTERCOMMUNAL / FP UNIQUE
CFE - GEMAPI / PRODUIT REEL NET INTERCOMMUNAL / FP UNIQUE
CFE - GEMAPI / NOMBRE ARTICLES INTERCOMMUNAL / FP UNIQUE
CFE - GEMAPI / BASE INTERCOMMUNALE / FPZ EN ZAE
CFE - GEMAPI / TAUX INTERCOMMUNAL / FPZ EN ZAE
CFE - GEMAPI / PRODUIT REEL NET INTERCOMMUNAL / FPZ EN ZAE
CFE - GEMAPI / NOMBRE ARTICLES INTERCOMMUNAL / FPZ EN ZAE
CFE - GEMAPI / BASE INTERCOMMUNALE / FPE EN ZONE EOLIENNE
CFE - GEMAPI / TAUX INTERCOMMUNAL / FPE EN ZONE EOLIENNE
CFE - GEMAPI / PRODUIT REEL NET INTERCOMMUNAL / FPE EN ZONE EOLIENNE
CFE - GEMAPI / NOMBRE ARTICLES INTERCOMMUNAL / FPE EN ZONE EOLIENNE
CFE - TASA / BASE NETTE
CFE - TASA / TAUX NET
CFE - TASA / PRODUIT REEL NET
CFE - TASA / NOMBRE ARTICLES
CFE - CHAMBRE DE COMMERCE ET INDUSTRIE /  BASE
CFE - CHAMBRE DE COMMERCE ET INDUSTRIE /  TAUX NET
CFE - CHAMBRE DE COMMERCE ET INDUSTRIE /  PRODUIT REEL NET
CFE - CHAMBRE DE COMMERCE ET INDUSTRIE /  NOMBRE ARTICLES
CFE - CHAMBRE DES METIERS /  DROIT FIXE / QUOTITE
CFE - CHAMBRE DES METIERS / DROIT FIXE / MONTANT
CFE - CHAMBRE DES METIERS / DROIT FIXE / NOMBRE D'ARTICLES
CFE - CHAMBRE DES METIERS /  DROIT ADDITIONNEL / BASE
CFE - CHAMBRES DES METIERS /  DROIT ADDITIONNEL / TAUX NET
CFE - CHAMBRE DES METIERS /  DROIT ADDITIONNEL / PRODUIT NET
CFE - CHAMBRE DES METIERS /  DROIT ADDITIONNEL / NOMBRE ARTICLES
CFE - FRAIS DE CONFECTION DES ROLES
CFE - TOTAL DES SOMMES MISES EN RECOUVREMENT
CFE - NOMBRE ARTICLES MIS EN RECOUVREMENT
CFE - COTISATIONS INFERIEURES A 12 EUROS / MONTANT
CFE - NOMBRE ARTICLES COMPORTANT UNE COTISATION INFERIEURE A 12 EUROS
CFE - CREDITS IMPOTS (1647 C SEPTIES) IMPUTES SUR LE TOTAL DES COTISATION / MONTANT
CFE - CREDITS IMPOTS (1647 C SEPTIES) IMPUTES SUR LE TOTAL DES COTISATION / NOMBRE
CFE - CREDITS IMPOTS (1647 C SEPTIES) A RESTITUER / MONTANT
CFE - CREDITS IMPOTS (1647 C SEPTIES) A RESTITUER / NOMBRE
CFE - CREDITS IMPOTS (1647 C SEPTIES) NON RESTITUES / MONTANT
CFE - CREDITS IMPOTS (1647 C SEPTIES) NON RESTITUES / NOMBRE
CFE - BASES BRUTES TOTALES (= T10+T15+T22) / MONTANT
CFE - NOMBRE ARTICLES COMPORTANT UNE BASE BRUTE

In [175]:
import duckdb
con = duckdb.connect()

df = con.sql("SELECT * FROM 'pipeline_inputs/budget_per_compte_communes.csv' LIMIT 5").df()
print(df)

IOException: IO Error: No files found that match the pattern "pipeline_inputs/budget_per_compte_communes.csv"

In [134]:
for t in con.sql("SHOW TABLES").fetchall():
    print(t, con.sql(f"SELECT COUNT(*) FROM {t[0]}").fetchone()[0])

('azi_gaspar',) 18864
('budget_communes',) 8329401
('budget_per_compte_communes',) 0
('catnat_gaspar',) 260799
('ccr_details',) 243032
('ccr_main_page',) 832
('datactivist_commune',) 35013
('dicrim_gaspar',) 9752
('insee_commune',) 37548
('insee_filosofi_2021',) 833400
('population_code_geo',) 34995
('pprm_gaspar',) 996
('pprn_gaspar',) 32424
('pprt_gaspar',) 2413
('primes_assurances_communes',) 711549
('res2_insee',) 278947

In [59]:
df_prime_assurances['siren'] = df_prime_assurances['siret'].astype(str).str[:9]

In [51]:
df.groupby(['code_departement','code_insee'])['siren'].nunique().loc[lambda x: x > 1]

code_departement  code_insee
001               6             2
                  10            2
                  25            2
                  33            2
                  36            3
                               ..
79                30            2
                  242           2
88                176           2
976               612           2
                  613           2
Name: siren, Length: 2077, dtype: int64

In [41]:
df.groupby('siren')['code_insee'].nunique().loc[lambda x: x > 1]

siren
200008712    2
200008720    2
200008738    2
200008746    2
200008753    2
            ..
219733052    2
219733094    3
219733532    2
219740040    2
219740222    2
Name: code_insee, Length: 4599, dtype: int64

In [45]:
df.loc[df['siren'] == '219740222', ['annee', 'code_insee','code_departement']].drop_duplicates()

        annee  code_insee code_departement
31880    2021         422              104
84645    2020         422              104
136653   2022         422              104
192331   2023         422              104
239836   2018         422              104
272090   2024         422              104
330972   2019         422              104
383154   2014         422              974
419811   2015         422              974
448463   2017         422              104
494965   2016         422              104
540971   2016         999              104
564832   2012         422              974
611910   2013         422              974
639497   2011         422              974
641041   2011        <NA>              974
672235   2010         422              974
698474   2010        <NA>              974

In [6]:
import pandas as pd

In [7]:
ls

LICENSE         d4g-utils/      pyproject.toml  uv.lock
README.md       data/           tox.ini         website/

In [8]:
df_ = pd.read_csv('data/dbt_pipeline/pipeline_inputs/primes_assurances_communes.csv')

In [9]:
ddf_ = pd.read_csv(
    'data/dbt_pipeline/pipeline_inputs/primes_assurances_communes.csv',
    dtype={
        'NDEPT': str,
        'CREGI': str,
        'INSEE': str,
        'IDENT': str
    }
)

In [43]:
ddf_['NDEPT'].dtype

In [5]:
df_budget = con.sql("SELECT * FROM budget_per_compte_communes").df()

In [6]:
con = duckdb.connect("data/dbt_pipeline/dev.duckdb")
df_budget = con.sql("SELECT * FROM budget_per_compte_communes").df()

In [129]:
con.sql("SELECT COUNT(*) FROM budget_per_compte_communes").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│            0 │
└──────────────┘

In [53]:
df['code_departement'] = df['code_departement'].str.replace(r'^0+(\d+)$', r'\1', regex=True)

In [54]:
df.loc[(df['code_departement'].str.len() == 3)]

,annee,siret,code_departement,code_insee,code_region,type_compte,solde_debiteur,solde_crediteur,solde,code_geo
36572,2010,21971101700018,971,101,1,depenses,75218403.36,182600.62,75035802.74,971101
36573,2010,21971102500011,971,102,1,depenses,6683509.87,9830.33,6673679.54,971102
36574,2010,21971103300015,971,103,1,depenses,62185650.03,29537.00,62156113.03,971103
36575,2010,21971104100018,971,104,1,depenses,6353861.63,7228.31,6346633.32,971104
36576,2010,21971105800012,971,105,1,depenses,20217788.66,33640.70,20184147.96,971105
...,...,...,...,...,...,...,...,...,...,...
2691321,2024,20000882900018,106,613,106,primes d assurances,26772.25,0.00,26772.25,106613
2691322,2024,20000885200010,106,614,106,primes d assurances,30557.30,0.00,30557.30,106614
2691323,2024,20000886000013,106,615,106,primes d assurances,59865.34,0.00,59865.34,106615
2691324,2024,20000887800015,106,616,106,primes d assurances,96251.39,0.00,96251.39,106616
2691325,2024,20000888600018,106,617,106,primes d assurances,51603.89,0.00,51603.89,106617

In [ ]:
df.loc[(df['code_departement'].str.len() == 3)][['code_departement','annee']].value_counts()

code_departement  annee
02B               2017     1153
                  2018     1152
                  2022     1152
                  2023     1146
                  2021     1142
                           ...
976               2014       64
                  2015       63
106               2016       63
                  2017       63
976               2013       62
Name: count, Length: 93, dtype: int64

In [61]:
pd.set_option('display.max_rows', None)

In [70]:
df.loc[(df['code_departement']=='974')][['code_departement','annee']].value_counts()

code_departement  annee
974               2013     93
                  2014     93
                  2015     93
                  2010     92
                  2012     92
                  2011     91
Name: count, dtype: int64

In [79]:
df.loc[(df['code_departement']=='975')][['code_departement','annee']].value_counts()

Series([], Name: count, dtype: int64)

In [62]:
df.loc[(df['code_departement'].str.len() == 3)][['code_departement','annee']].value_counts()

code_departement  annee
02B               2017     1153
                  2018     1152
                  2022     1152
                  2023     1146
                  2021     1142
                  2016     1138
                  2020     1137
                  2019     1107
                  2024      886
02A               2023      698
                  2022      688
                  2016      687
                  2017      686
                  2018      684
                  2020      677
                  2021      675
                  2019      647
                  2024      474
104               2017      278
                  2016      277
                  2018      275
                  2019      262
101               2021      169
                  2016      167
                  2022      167
                  2017      166
                  2020      165
                  2023      164
                  2018      160
104               2022      159
101               2019      158
104               2021      158
                  2020      157
103               2016      156
                  2017      156
104               2023      156
103               2018      154
                  2023      154
                  2022      152
                  2020      151
                  2021      151
                  2019      144
972               2010      136
                  2012      136
                  2013      136
                  2011      135
                  2014      135
103               2024      135
972               2015      134
971               2015      128
                  2010      127
                  2011      127
                  2012      127
                  2013      127
                  2014      127
101               2024      127
102               2021      125
                  2022      121
                  2023      119
                  2018      117
                  2019      117
                  2020      117
                  2016      116
                  2017      116
974               2013       93
                  2014       93
                  2015       93
104               2024       93
974               2010       92
                  2012       92
                  2011       91
973               2015       86
102               2024       86
973               2010       85
                  2013       85
                  2014       85
                  2012       84
                  2011       83
106               2020       72
                  2021       72
                  2022       72
                  2023       72
                  2024       68
976               2011       67
106               2019       67
976               2010       66
106               2018       66
976               2012       65
                  2014       64
                  2015       63
106               2016       63
                  2017       63
976               2013       62
Name: count, dtype: int64

In [58]:
set(df.loc[(df['code_departement'].str.len() == 3)]['code_departement'])

{'02A',
 '02B',
 '101',
 '102',
 '103',
 '104',
 '106',
 '971',
 '972',
 '973',
 '974',
 '976'}

In [10]:
# df.loc[(df['code_departement']=='102')]

In [ ]:
101 - 971

In [11]:
import requests

url = "https://www.data.gouv.fr/api/1/datasets/r/42b16d68-958e-4518-8551-93e095fe8fda"
response = requests.get(url)

In [20]:
import requests

url = "https://www.data.gouv.fr/api/1/datasets/r/42b16d68-958e-4518-8551-93e095fe8fda"

response = requests.get(url)
if response.status_code == 200:
    with open("table_siren_insee.zip", "wb") as f:
        f.write(response.content)
    print("Téléchargement OK")
else:
    print("Erreur", response.status_code)

Erreur 404

In [35]:
cd Documents/GitHub/14_PrixChangementClimatique/

/Users/chloe/Documents/GitHub/14_PrixChangementClimatique

In [36]:
sireninsee = pd.read_csv('data/exploration/banatic-sireninsee-last.csv', encoding="ISO-8859-1",sep=';')

In [55]:
sireninsee.to_csv('data/exploration/table_siren_insee.csv')

In [168]:
sireninsee

,Reg_com,dep_com,siren,insee,nom_com,ptot_2024,pmun_2024,pcap_2024
0,84,01,210100012,01001,L'Abergement-Clémenciat,848,832,16
1,84,01,210100020,01002,L'Abergement-de-Varey,273,267,6
2,84,01,210100046,01004,Ambérieu-en-Bugey,15 240,14 854,386
3,84,01,210100053,01005,Ambérieux-en-Dombes,1 921,1 897,24
4,84,01,210100061,01006,Ambléon,113,113,0
...,...,...,...,...,...,...,...,...
34930,6,976,200008829,97613,M'Tsangamouji,6 586,6 432,154
34931,6,976,200008852,97614,Ouangani,10 393,10 203,190
34932,6,976,200008860,97615,Pamandzi,11 802,11 442,360
34933,6,976,200008878,97616,Sada,11 619,11 156,463
34934,6,976,200008886,97617,Tsingoni,14 235,13 934,301

In [64]:
sireninsee['siren'] = sireninsee['siren'].astype(str)

In [65]:
df_prime_assurances_ = df_prime_assurances.merge(sireninsee[['siren','insee','nom_com']], on= 'siren',how='left')

In [116]:
df_prime_assurances_test = df_prime_assurances_[['siren','code_departement','code_insee']]

In [117]:
df_prime_assurances_test = df_prime_assurances_test.drop_duplicates()

In [118]:
df_prime_assurances_test

            siren code_departement code_insee
0       211700356               17        035
1       210200325               02        032
2       215505041               55        504
3       215700584               57        058
4       218601821               86        182
...           ...              ...        ...
710447  215105321               51        NaN
710574  211300652               13        NaN
710649  210202792               02        NaN
710812  213905425               39        NaN
711330  211200357               12        NaN

[51812 rows x 3 columns]

In [ ]:
df_prime_assurances_.loc[df_prime_assurances_['diff'] == False]

,annee,siret,code_departement,code_insee,code_region,compte,solde_debiteur,solde_crediteur,code_geo,siren,insee,nom_com,diff
20,2021,21972209700777,103,996,103,6168,2411.40,0.0,103996,219722097,97209,Fort-de-France,False
34,2021,21880196700272,88,960,44,6168,4422.51,0.0,88960,218801967,88196,Gérardmer,False
48,2021,21210603300344,21,NaN,27,6163,9672.25,0.0,NaN,212106033,21603,Semur-en-Auxois,False
61,2021,20006146300127,22,950,53,6161,23.10,0.0,22950,200061463,22055,Binic-Étables-sur-Mer,False
63,2021,21560069300075,56,855,53,6161,5513.86,0.0,56855,215600693,56069,Groix,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
711525,2010,21790285700010,79,285,54,616,5612.16,0.0,79285,217902857,NaN,NaN,False
711528,2010,21250530900014,25,530,43,616,4235.68,0.0,25530,212505309,NaN,NaN,False
711537,2010,21330106200013,33,106,72,616,18970.01,0.0,33106,213301062,NaN,NaN,False
711539,2010,21380284600013,38,284,82,616,1287.20,0.0,38284,213802846,NaN,NaN,False
711548,2010,21010343800037,01,NaN,82,616,1873.02,0.0,NaN,210103438,01343,Saint-Cyr-sur-Menthon,False

In [140]:
df_budget['code_departement'] = (
    df_budget['code_departement'].astype(str).str.lstrip('0').str.zfill(2)
)
df_budget['code_departement'] = (
    df_budget['code_departement'].astype(str).str.lstrip('0').str.zfill(2)
)

In [ ]:
df_budget['siren'] = df_budget['siret'].astype(str).str[:9]

In [146]:
COMMUNES  = df_budget[['siren','code_insee','code_departement']].drop_duplicates()

In [74]:
df_prime_assurances_['code_departement'] = (
    df_prime_assurances_['code_departement'].astype(str).str.lstrip('0').str.zfill(2)
)

In [78]:
df_prime_assurances_['code_insee'] = (
    df_prime_assurances_['code_insee'].astype(str).str.zfill(3)
)

In [80]:
df_prime_assurances_['code_geo'] = df_prime_assurances_['code_departement'] + df_prime_assurances_['code_insee']

In [ ]:
df_prime_assurances_['code_geo'] = df_prime_assurances_['code_geo'].astype(str)
df_prime_assurances_['code_geo'] = df_prime_assurances_['code_geo'].astype(str)

In [96]:
df_prime_assurances__ = df_prime_assurances_.merge(sireninsee[['siren','insee','nom_com']], left_on= 'code_geo',right_on = 'insee',how='left')

In [85]:
df_prime_assurances_['diff'] = df_prime_assurances_['code_geo'] == df_prime_assurances_['insee']

In [99]:
df_prime_assurances__.loc[~(df_prime_assurances__['siren_y'].isna())]

,annee,siret,code_departement,code_insee,code_region,compte,solde_debiteur,solde_crediteur,code_geo,siren_x,insee_x,nom_com_x,diff,siren_y,insee_y,nom_com_y
0,2021,21170035600010,17,035,75,6161,1618.92,0.0,17035,211700356,17035,Bazauges,True,211700356,17035,Bazauges
1,2021,21020032500012,02,032,32,6168,866.22,0.0,02032,210200325,02032,Aubigny-aux-Kaisnes,True,210200325,02032,Aubigny-aux-Kaisnes
2,2021,21550504100016,55,504,44,6161,5138.16,0.0,55504,215505041,55504,Tannois,True,215505041,55504,Tannois
3,2021,21570058400208,57,058,44,6161,46737.03,0.0,57058,215700584,57058,Behren-lès-Forbach,True,215700584,57058,Behren-lès-Forbach
4,2021,21860182100018,86,182,75,6168,694.00,0.0,86182,218601821,86182,Orches,True,218601821,86182,Orches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711543,2010,21232190500011,23,219,74,616,4147.06,0.0,23219,212321905,23219,Saint-Maurice-la-Souterraine,True,212321905,23219,Saint-Maurice-la-Souterraine
711544,2010,21400240400017,40,240,72,616,6806.36,0.0,40240,214002404,40240,Renung,True,214002404,40240,Renung
711545,2010,21840005900018,84,005,93,616,1829.45,0.0,84005,218400059,84005,Aurel,True,218400059,84005,Aurel
711546,2010,21840112300011,84,112,93,616,9424.80,0.0,84112,218401123,84112,Saint-Martin-de-Castillon,True,218401123,84112,Saint-Martin-de-Castillon
711547,2010,21780082000011,78,082,11,616,3125.73,0.0,78082,217800820,78082,Boissy-Mauvoisin,True,217800820,78082,Boissy-Mauvoisin

In [87]:
df_prime_assurances_['diff'].value_counts()

diff
True     623031
False     88518
Name: count, dtype: int64

In [94]:
df_prime_assurances_.loc[df_prime_assurances_['code_insee'].isna()]

,annee,siret,code_departement,code_insee,code_region,compte,solde_debiteur,solde_crediteur,code_geo,siren,insee,nom_com,diff
48,2021,21210603300344,21,NaN,27,6163,9672.25,0.0,NaN,212106033,21603,Semur-en-Auxois,False
2164,2021,21930046400274,93,NaN,11,61688,3859.03,0.0,NaN,219300464,93046,Livry-Gargan,False
4930,2021,21220379800088,22,NaN,53,6161,1979.49,0.0,NaN,212203798,22379,Trévou-Tréguignec,False
6888,2021,21770350300169,77,NaN,11,6161,4986.00,0.0,NaN,217703503,77350,Ozoir-la-Ferrière,False
7610,2021,21200004600459,2A,NaN,94,6161,3382.08,0.0,NaN,212000046,2A004,Ajaccio,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
711509,2010,21290086400043,29,NaN,53,616,323.94,0.0,NaN,212900864,29086,Irvillac,False
711512,2010,21700486000029,70,NaN,43,616,822.83,0.0,NaN,217004860,70486,Semmadon,False
711519,2010,21420237600106,42,NaN,82,616,2402.92,0.0,NaN,214202376,42237,Saint-Jean-Bonnefonds,False
711522,2010,21830031700045,83,NaN,93,6168,915.69,0.0,NaN,218300317,83031,Le Cannet-des-Maures,False
711548,2010,21010343800037,01,NaN,82,616,1873.02,0.0,NaN,210103438,01343,Saint-Cyr-sur-Menthon,False

In [95]:
df_prime_assurances_.loc[df_prime_assurances_['insee'].isna()]

,annee,siret,code_departement,code_insee,code_region,compte,solde_debiteur,solde_crediteur,code_geo,siren,insee,nom_com,diff
399,2021,21850307600042,85,861,52,6168,2100.00,0.0,85861,218503076,NaN,NaN,False
1139,2021,21160186900046,16,434,75,6161,291.00,0.0,16434,211601869,NaN,NaN,False
1172,2021,21020053100015,02,054,32,6161,2428.65,0.0,02054,210200531,NaN,NaN,False
1773,2021,20006018400013,49,160,52,6161,12372.69,0.0,49160,200060184,NaN,NaN,False
2084,2021,21020076200016,02,077,32,6161,2229.07,0.0,02077,210200762,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
711517,2010,21730238900010,73,238,82,616,2198.07,0.0,73238,217302389,NaN,NaN,False
711525,2010,21790285700010,79,285,54,616,5612.16,0.0,79285,217902857,NaN,NaN,False
711528,2010,21250530900014,25,530,43,616,4235.68,0.0,25530,212505309,NaN,NaN,False
711537,2010,21330106200013,33,106,72,616,18970.01,0.0,33106,213301062,NaN,NaN,False
711539,2010,21380284600013,38,284,82,616,1287.20,0.0,38284,213802846,NaN,NaN,False

In [102]:
df_prime_assurances__False = df_prime_assurances__.loc[df_prime_assurances__['diff']==False]

In [107]:
df_prime_assurances__False.loc[~((df_prime_assurances__False['insee_y'].isna()|(df_prime_assurances__False['insee_x'].isna())))]

,annee,siret,code_departement,code_insee,code_region,compte,solde_debiteur,solde_crediteur,code_geo,siren_x,insee_x,nom_com_x,diff,siren_y,insee_y,nom_com_y
167,2021,21620272100033,62,838,32,616,200.64,0.0,62838,216202721,62272,Douchy-lès-Ayette,False,216208389,62838,Vaulx
1372,2021,21620413100207,62,858,32,6161,251.98,0.0,62858,216204131,62413,Harnes,False,216208587,62858,Villers-lès-Cagnicourt
1495,2021,20005734700078,01,123,84,6161,727.08,0.0,01123,200057347,01426,Val-Revermont,False,210101234,01123,Cormoranche-sur-Saône
2086,2021,21620726600034,62,861,32,6161,634.41,0.0,62861,216207266,62726,Ruisseauville,False,216208611,62861,Vimy
3777,2021,21700122100068,70,014,27,616,5726.21,0.0,70014,217001221,70122,Champlitte,False,217000140,70014,Amblans-et-Velotte
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542570,2016,21620671400034,62,891,32,616,367.03,0.0,62891,216206714,62671,Pronville-en-Artois,False,216208918,62891,Willencourt
543151,2016,21010116800057,01,151,84,6162,6710.69,0.0,01151,210101168,01116,Contrevoz,False,210101515,01151,Druillat
543152,2016,21220127100054,22,002,53,6161,373.60,0.0,22002,212201271,22127,Lézardrieux,False,212200026,22002,Andel
544000,2016,20005734700078,01,123,84,6161,1369.61,0.0,01123,200057347,01426,Val-Revermont,False,210101234,01123,Cormoranche-sur-Saône
544056,2016,21800637700079,80,740,32,6161,1147.32,0.0,80740,218006377,80677,Roisel,False,218006930,80740,Sourdon

In [109]:
df_prime_assurances__False.loc[~(((df_prime_assurances__False['code_geo'].isna())))]

,annee,siret,code_departement,code_insee,code_region,compte,solde_debiteur,solde_crediteur,code_geo,siren_x,insee_x,nom_com_x,diff,siren_y,insee_y,nom_com_y
20,2021,21972209700777,103,996,103,6168,2411.40,0.0,103996,219722097,97209,Fort-de-France,False,NaN,NaN,NaN
34,2021,21880196700272,88,960,44,6168,4422.51,0.0,88960,218801967,88196,Gérardmer,False,NaN,NaN,NaN
61,2021,20006146300127,22,950,53,6161,23.10,0.0,22950,200061463,22055,Binic-Étables-sur-Mer,False,NaN,NaN,NaN
63,2021,21560069300075,56,855,53,6161,5513.86,0.0,56855,215600693,56069,Groix,False,NaN,NaN,NaN
79,2021,21220021600050,22,883,53,6161,265.59,0.0,22883,212200216,22021,Brusvily,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711517,2010,21730238900010,73,238,82,616,2198.07,0.0,73238,217302389,NaN,NaN,False,NaN,NaN,NaN
711525,2010,21790285700010,79,285,54,616,5612.16,0.0,79285,217902857,NaN,NaN,False,200082873,79285,Saint-Pardoux-Soutiers
711528,2010,21250530900014,25,530,43,616,4235.68,0.0,25530,212505309,NaN,NaN,False,NaN,NaN,NaN
711537,2010,21330106200013,33,106,72,616,18970.01,0.0,33106,213301062,NaN,NaN,False,200064301,33106,Castets et Castillon
711539,2010,21380284600013,38,284,82,616,1287.20,0.0,38284,213802846,NaN,NaN,False,200083038,38284,Ornacieux-Balbins

In [147]:
COMMUNES

             siren  code_insee code_departement
0        210100012           1               01
1        210100103          10               01
2        210101002         100               01
3        210101010         101               01
4        210101028         102               01
...            ...         ...              ...
2094894  218600682         466               86
2095874  218800795         671               88
2095895  218800761         728               88
2097382  219711033         104              101
2097413  219711066         927              101

[92731 rows x 3 columns]

In [165]:
COMMUNES = pd.read_csv("data/exploration/check_communes.csv")

In [166]:
COMMUNES['siren'] = COMMUNES['IDENT'].astype(str).str[:9]

In [ ]:
df_prime_assurances_['code_insee'] = (
    df_prime_assurances_['code_insee'].astype(str).str.zfill(3)
)

In [175]:
COMMUNES['code_departement'] = (
    COMMUNES['NDEPT'].astype(str).str.lstrip('0').str.zfill(2)
)
COMMUNES['code_insee'] = (
    COMMUNES['INSEE'].astype(str).str.zfill(3)
)

In [179]:
COMMUNES['code_insee'] == [int(i) for i in COMMUNES['code_insee']]

ValueError: invalid literal for int() with base 10: '257.0'

In [159]:
COMMUNES = COMMUNES[['code_departement','code_insee','siren','IDENT']]

In [160]:
COMMUNES_ = COMMUNES.merge(sireninsee[['siren','insee','nom_com']], on= 'siren',how='left')

In [ ]:
COMMUNES_ = COMMUNES.merge(sireninsee[['siren','insee','nom_com']], on= 'siren',how='left')
COMMUNES_['code_geo'] = COMMUNES_['code_departement']+COMMUNES_['code_insee']

In [162]:
COMMUNES_['diff'] = COMMUNES_['code_geo'] == COMMUNES_['code_insee']

In [183]:
COMMUNES_[['siren','code_insee']].drop_duplicates()

            siren code_insee
0       216902577      257.0
1       216902668      266.0
2       218602134      213.0
3       218300978       97.0
4       218602217      221.0
...           ...        ...
195344  217004373        NaN
195350  213904451        NaN
195352  212002463        NaN
195353  217003169        NaN
195357  213402449        NaN

[116330 rows x 2 columns]

In [181]:
len(set(COMMUNES_['siren']))

37564

In [ ]:
len(set(COMMUNES_['siren']))

In [26]:
cd ~

/Users/chloe

In [27]:
import glob
import pandas as pd

cols_to_keep = ["EXER","NDEPT","CREGI",
    "INSEE","COMPTE","IDENT","SD","SC"
]

balances = {}

for file in glob.glob('Dropbox/DataForGood/data/balances*'):
    year = int(file.split('.')[0][-4:])
    try:
        balance = pd.read_csv(
            file,
            engine="pyarrow",
            sep=";",
            usecols=cols_to_keep,dtype={        "COMPTE": "string",
        "INSEE": "string",   # 👈 ajoute ça
        "SIREN": "string"}  
        )
        
        balances[year] = balance
        print(year, "download")
        
    except Exception as e:
        print(year, "error:", e)

2021 download
2020 download
2022 download
2023 download
2018 download
2024 download
2019 download
2014 download
2015 download
2017 download
2016 download
2012 download
2013 download
2011 download
2010 download

In [32]:
dic = {'16':'dettes','616':'prime d\'assurance','7':'produits','6':'depenses','21': 'immo corporelle',
    '20': 'immo incorporelle',
    '23': 'immo en cours',
    '25': 'immo financière',
    '26': 'immo financière',
    '27': 'immo financière',
    '28': 'amortissements',
    '29': 'dépréciations'}

In [54]:
def type_compte(compte):
    compte_str = str(compte)
    # Vérifie si le compte commence par une clé du dictionnaire
    for key in dic:
        if compte_str.startswith(key):
            return dic[key]
    # Si commence par '2' mais pas dans dic_
    if compte_str.startswith('2'):
        return 'autres immo'
    return 'inconnu'

In [ ]:
budgets['categorie'] = budgets['COMPTE'].astype(str).apply(type_compte)

In [ ]:
budgets['categorie'].value_counts()

categorie
depenses             30528822
produits             15034761
immo corporelle      13096303
amortissements        2724092
immo incorporelle     1997045
dettes                1519431
immo en cours          976697
immo financière        968294
prime d'assurance      711549
autres                 564145
dépréciations            1174
Name: count, dtype: int64

In [50]:
budget_per_compte_list = []

for code in start:
    df_compte = budgets.loc[budgets['COMPTE'].astype(str).str.startswith(code)]
    if df_compte.empty:
        continue
    df_compte_grouped = (
        df_compte
        .groupby(["EXER","NDEPT","CREGI","INSEE","IDENT",'categorie'], as_index=False)[["SD","SC"]]
        .sum()
    )
    # df_compte_grouped['categorie'] = df_compte_grouped['COMPTE'].astype(str).apply(type_compte)
    budget_per_compte_list.append(df_compte_grouped)

budget_per_compte = pd.concat(budget_per_compte_list, ignore_index=True)

In [45]:
import numpy as np

In [51]:
def safe_int(x):
    try:
        return int(x)
    except ValueError:
        return x  # garde la valeur originale si ce n'est pas un nombre

budget_per_compte['NDEPT'] = budget_per_compte['NDEPT'].apply(safe_int)
budget_per_compte['INSEE'] = budget_per_compte['INSEE'].apply(safe_int)


budget_per_compte = budget_per_compte.replace(np.nan,'empty')

In [52]:
budget_per_compte.columns

Index(['EXER', 'NDEPT', 'CREGI', 'INSEE', 'IDENT', 'categorie', 'SD', 'SC'], dtype='str')

In [53]:
budget_per_compte['categorie'].value_counts()

categorie
immo corporelle      1391820
immo incorporelle    1150674
immo financière      1133794
prime d'assurance    1120550
amortissements        999058
immo en cours         874880
produits              744479
depenses              739487
dettes                646972
autres                337136
dépréciations           1944
Name: count, dtype: int64

In [28]:


start = ['16','616','7','6','21','20','23','25','26','27','28','29','2']

budgets = pd.DataFrame({})

for year, balance in balances.items():
    balance['COMPTE'] = balance['COMPTE'].astype(str)
    
    # str.startswith accepte une tuple
    mask = balance['COMPTE'].str.startswith(tuple(start))
    budg = balance.loc[mask]
    
    budgets = pd.concat([budgets, budg])

In [ ]:
start = ['16','616','7','6','21','20','23','25','26','27','28','29','2'],
budgets = pd.DataFrame({})
for year, balance in balances.items():
    balance['COMPTE'] = balance['COMPTE'].astype(str)
    budg = balance.loc[((balance['COMPTE'].str.startswith("16")) |(balance['COMPTE'].str.startswith("616")) |(balance['COMPTE'].str.startswith("6")) | (balance['COMPTE'].str.startswith("7")))]
    budgets = pd.concat([budgets,budg])

In [143]:
prime_assurance = pd.DataFrame({})
for year, balance in balances.items():
    balance['COMPTE'] = balance['COMPTE'].astype(str)
    prime = balance.loc[(((balance['COMPTE'].str.startswith("616"))))]
    prime_assurance = pd.concat([prime_assurance,prime])

In [144]:
prime_assurance = prime_assurance.replace(np.nan,'empty')

In [145]:
def safe_int(x):
    try:
        return int(x)
    except ValueError:
        return x  # garde la valeur originale si ce n'est pas un nombre

prime_assurance['NDEPT'] = prime_assurance['NDEPT'].apply(safe_int)
prime_assurance['INSEE'] = prime_assurance['INSEE'].apply(safe_int)

In [119]:
budgets = budgets.replace(np.nan,'empty')

In [123]:
group_cols = ["EXER","NDEPT","CREGI","INSEE","COMPTE","IDENT"]

budgets_total = (
    budgets
    .groupby(group_cols, as_index=False)[
        ["SD","SC"]
    ]
    .sum()
)

In [139]:
budgets_total.shape

(47794563, 8)

In [130]:
dic_ = {'7':'produits','6':'depenses','616':'primes d assurances','16':'dettes financieres'}
budget_per_compte_list = []
for compte in ['6','7','16','616']:
    df_compte = budgets_total.loc[budgets_total['COMPTE'].str.startswith(compte)]
    df_compte_grouped = (
    df_compte
    .groupby(["EXER","NDEPT","CREGI","INSEE","IDENT"], as_index=False)[
        ["SD","SC"]
    ]
    .sum()
    )
    df_compte_grouped['type_compte'] = dic_[compte]
    budget_per_compte_list.append(df_compte_grouped)

budget_per_compte = pd.concat(budget_per_compte_list, ignore_index=True)

In [140]:
budget_per_compte.shape

(3312434, 8)

In [106]:
# budget_per_compte['code_departement'] = (
#     budget_per_compte['NDEPT'].astype(str).str.lstrip('0').str.zfill(2)
# )
# budget_per_compte['code_insee'] = (
#     budget_per_compte['INSEE'].astype(str).str.zfill(3)
# )

In [132]:
def safe_int(x):
    try:
        return int(x)
    except ValueError:
        return x  # garde la valeur originale si ce n'est pas un nombre

budget_per_compte['NDEPT'] = budget_per_compte['NDEPT'].apply(safe_int)
budget_per_compte['INSEE'] = budget_per_compte['INSEE'].apply(safe_int)

In [148]:
budget_per_compte['NDEPT'] = budget_per_compte['NDEPT'].astype(str)
budget_per_compte['INSEE'] = budget_per_compte['INSEE'].astype(str)

In [152]:
budget_per_compte.to_csv('Documents/GitHub/14_PrixChangementClimatique/data/dbt_pipeline/pipeline_inputs/budget_per_compte_communes_clean.csv')

In [150]:
prime_assurance['NDEPT'] = prime_assurance['NDEPT'].astype(str)
prime_assurance['INSEE'] = prime_assurance['INSEE'].astype(str)

In [151]:
prime_assurance.to_csv('Documents/GitHub/14_PrixChangementClimatique/data/dbt_pipeline/pipeline_inputs/primes_assurances_communes_clean.csv')

In [40]:
import sqlite3
import pandas as pd

# connexion SQLite en mémoire
conn = sqlite3.connect(":memory:")

# envoyer ton dataframe dans SQLite
budget_per_compte.to_sql("budget_insee", conn, index=False, if_exists="replace")
sireninsee.to_sql("sireninsee", conn, index=False, if_exists="replace")
# requête SQL
query = """
WITH transformed AS (SELECT
    -- Transformation du code département
    CASE
        WHEN LENGTH(printf('%02d', CAST(NDEPT AS INTEGER))) = 3
             AND SUBSTR(printf('%02d', CAST(NDEPT AS INTEGER)), 1, 2) = '10'
        THEN '97'
        ELSE printf('%02d', CAST(NDEPT AS INTEGER))
    END AS code_departement,

    -- Transformation du code INSEE
    CASE
        WHEN SUBSTR(printf('%02d', CAST(NDEPT AS INTEGER)), 1, 2) = '97'
        THEN SUBSTR(printf('%02d', CAST(NDEPT AS INTEGER)), -1, 1) || printf('%02d', INSEE)
        ELSE printf('%03d', INSEE)
    END AS code_insee,
    IDENT AS siret,
    SUBSTR(IDENT, 1, 9) AS siren,
        EXER AS annee,
    CREGI AS code_region,
    type_compte AS type_compte,
    SD AS solde_debiteur,
    SC AS solde_crediteur
FROM budget_insee)
SELECT
    t.*,
    t.code_departement || t.code_insee AS code_geo,
    s.insee AS insee_siren,
    s.nom_com
FROM transformed t
LEFT JOIN sireninsee s
    ON t.siren = s.siren;
"""

result = pd.read_sql(query, conn)
result.head()

,code_departement,code_insee,siret,siren,annee,code_region,type_compte,solde_debiteur,solde_crediteur,code_geo,insee_siren,nom_com
0,01,001,21010001200017,210100012,2010,82,depenses,329891.87,5999.38,01001,01001,L'Abergement-Clémenciat
1,01,010,21010010300014,210100103,2010,82,depenses,1160202.00,590.23,01010,01010,Anglefort
2,01,100,21010100200017,210101002,2010,82,depenses,101188.40,0.00,01100,01100,Cheignieu-la-Balme
3,01,101,21010101000010,210101010,2010,82,depenses,138281.77,0.00,01101,01101,Chevillard
4,01,102,21010102800012,210101028,2010,82,depenses,344885.95,1636.00,01102,01102,Chevroux

In [25]:
result_= result.loc[result['code_departement'].str.len()>2]

In [27]:
result_= result.loc[result['code_departement'].str.startswith('10')]

In [29]:
result_ = result_.loc[result['code_departement'].str.len()>2]

In [30]:
result_

        code_departement code_insee           siret
286518               101        101  21971101700018
286519               101        102  21971102500011
286520               101        103  21971103300015
286521               101        104  21971104100018
286522               101        105  21971105800012
...                  ...        ...             ...
2691321              106        613  20000882900018
2691322              106        614  20000885200010
2691323              106        615  20000886000013
2691324              106        616  20000887800015
2691325              106        617  20000888600018

[6260 rows x 3 columns]

In [ ]:
# extraire le dernier chiffre de code_departement
result_= result.loc[result['code_departement'].str.startswith('97')]
dernier_dept = result_['code_departement'].str[-1]

# extraire le premier chiffre de code_insee
premier_insee = result_['code_insee'].str[0]

# filtrer
df_filtre = result_[dernier_dept != premier_insee]

# afficher
print(df_filtre)

        code_departement code_insee           siret
36684                976        501  20000871200016
36685                976        502  20000872000019
36686                976        503  20000873800011
36687                976        504  20000874600014
36688                976        505  20000875300010
...                  ...        ...             ...
2204119              976        513  20000884500014
2204120              976        514  20000885200010
2204121              976        515  20000886000013
2204122              976        516  20000887800015
2204123              976        517  20000888600018

[133 rows x 3 columns]

In [264]:
budget_insee = budgets[['NDEPT','INSEE','IDENT']].drop_duplicates()

In [265]:
budget_insee['siren'] = budget_insee['IDENT'].astype(str).str[:9]

In [266]:
budget_insee['code_departement'] = (
    budget_insee['NDEPT'].astype(str).str.lstrip('0').str.zfill(2)
)
budget_insee['code_insee'] = (
    budget_insee['INSEE'].astype(str).str.zfill(3)
)

In [267]:
budget_insee = budget_insee.merge(sireninsee[['siren','insee','nom_com']], on= 'siren',how='left')
budget_insee['code_geo'] = budget_insee['code_departement']+budget_insee['code_insee']

In [299]:
budget_insee['match_insee'] = budget_insee['insee'] == budget_insee['code_geo']

In [316]:
budget_insee[['code_departement','code_insee']].drop_duplicates()

       code_departement code_insee
0                    69        257
1                    69        266
2                    86        213
3                    83        097
4                    86        221
...                 ...        ...
191837              976        501
191864              976        512
191880               44        060
191901              976        506
191952              976        511

[58616 rows x 2 columns]

In [302]:
budget_insee.loc[~(budget_insee['match_insee']==True)]

,NDEPT,INSEE,IDENT,siren,code_departement,code_insee,insee,nom_com,code_geo,match_insee
14,083,877,21830043200042,218300432,83,877,83043,Collobrières,83877,False
19,070,903,21700311000186,217003110,70,903,70311,Luxeuil-les-Bains,70903,False
27,068,824,21680209000045,216802090,68,824,68209,Mittelwihr,68824,False
31,026,850,21260008400041,212600084,26,850,26008,Ancône,26850,False
33,024,966,21240145900061,212401459,24,966,24145,Creysse,24966,False
...,...,...,...,...,...,...,...,...,...,...
195355,55,<NA>,21550463000132,215504630,55,NaN,55463,Saint-Mihiel,NaN,False
195356,52,<NA>,21520324100116,215203241,52,NaN,NaN,NaN,NaN,False
195357,34,<NA>,21340244900044,213402449,34,NaN,34244,Saint-Brès,NaN,False
195358,19,<NA>,21192640700050,211926407,19,NaN,19264,Soursac,NaN,False
195359,15,<NA>,21150068100047,211500681,15,NaN,NaN,NaN,NaN,False

In [295]:
budget_insee['code_geo'] = budget_insee['code_geo'].astype(str)
budget_insee['insee'] = budget_insee['insee'].astype(str)

In [305]:
len(set(budget_insee['siren']))

37564

In [303]:
budget_insee['match_insee'].value_counts(dropna=False)

match_insee
False    125821
True      69539
Name: count, dtype: int64

In [304]:
budget_insee[['insee','code_geo']].isna().sum()

insee        9208
code_geo    66391
dtype: int64

In [272]:
budget_insee.loc[
    (budget_insee['insee'].notna()) &
    (budget_insee['code_geo'].notna()) &
    (budget_insee['insee'] != budget_insee['code_geo'])
].shape[0]

53764

In [273]:
siren_multi_insee = (
    budget_insee
    .groupby('siren')['insee']
    .nunique()
)

siren_multi_insee[siren_multi_insee > 1].count()

np.int64(0)

In [306]:
mask_diff = budget_insee['code_geo'].notna() & budget_insee['insee'].notna() & (budget_insee['insee'] != budget_insee['code_geo'])

# Nombre de lignes différentes
nb_lignes_diff = mask_diff.sum()

# Nombre de codes_geo différents concernés
nb_codegeo_diff_match = budget_insee.loc[mask_diff, 'code_geo'].nunique()

nb_lignes_diff, nb_codegeo_diff_match

(np.int64(53764), 23082)

In [275]:
budget_insee.loc[budget_insee['insee'].isna()]

,NDEPT,INSEE,IDENT,siren,code_departement,code_insee,insee,nom_com,code_geo,match_insee
793,016,355,21160355000057,211603550,16,355,NaN,NaN,16355,False
2395,016,140,21160140600013,211601406,16,140,NaN,NaN,16140,False
2619,016,206,21160206500016,211602065,16,206,NaN,NaN,16206,False
2911,049,321,21490321300012,214903213,49,321,NaN,NaN,49321,False
3019,085,37,21850037900019,218500379,85,037,NaN,NaN,85037,False
...,...,...,...,...,...,...,...,...,...,...
195333,14,<NA>,21140255700030,211402557,14,NaN,NaN,NaN,NaN,False
195338,24,<NA>,21240364600103,212403646,24,NaN,NaN,NaN,NaN,False
195341,01,<NA>,21010182000046,210101820,01,NaN,NaN,NaN,NaN,False
195356,52,<NA>,21520324100116,215203241,52,NaN,NaN,NaN,NaN,False
195359,15,<NA>,21150068100047,211500681,15,NaN,NaN,NaN,NaN,False

In [312]:
budget_insee[['siren','insee']].drop_duplicates()

            siren  insee
0       216902577  69257
1       216902668  69266
2       218602134  86213
3       218300978  83097
4       218602217  86221
...           ...    ...
188380  218802825    NaN
188449  214902132    NaN
191585  212803613    NaN
191611  212800429    NaN
193702  215901836    NaN

[37564 rows x 2 columns]

In [276]:
budget_insee.loc[mask_diff, 'code_geo']

14         83877
19         70903
27         68824
31         26850
33         24966
           ...
191834    976505
191837    976501
191864    976512
191901    976506
191952    976511
Name: code_geo, Length: 53764, dtype: str

In [277]:
siren_par_dep_insee = (
    budget_insee
    .groupby(['code_departement','INSEE'])
    .agg(
        n_siren = ('siren','nunique'),
        n_insee_na = ('INSEE', lambda x: x.isna().sum())
    )
    .reset_index()
)
siren_par_dep_insee

      code_departement INSEE  n_siren  n_insee_na
0                   01     1        2           0
1                   01    10        2           0
2                   01   100        1           0
3                   01   101        1           0
4                   01   102        2           0
...                ...   ...      ...         ...
58506              976   613        2           0
58507              976   614        1           0
58508              976   615        1           0
58509              976   616        1           0
58510              976   617        1           0

[58511 rows x 4 columns]

In [278]:
siren_na = budget_insee['siren'].isna().sum()

In [342]:
budget_insee.drop_duplicates()

,siren,code_departement,code_insee,insee,nom_com,code_geo,match_insee
0,216902577,69,257,69257,Vaux-en-Beaujolais,69257,True
1,216902668,69,266,69266,Villeurbanne,69266,True
2,218602134,86,213,86213,Rouillé,86213,True
3,218300978,83,097,83097,Pourrières,83097,True
4,218602217,86,221,86221,Saint-Genest-d'Ambière,86221,True
...,...,...,...,...,...,...,...
195344,217004373,70,NaN,70437,Ranzevelle,NaN,False
195350,213904451,39,NaN,39445,Publy,NaN,False
195352,212002463,2B,NaN,2B246,La Porta,NaN,False
195353,217003169,70,NaN,70316,Le Magnoray,NaN,False
195357,213402449,34,NaN,34244,Saint-Brès,NaN,False

In [339]:
insee_na = budget_insee['code_insee'].isna().sum()
print(insee_na)

66391

In [281]:
ndep_long = budget_insee[budget_insee['code_departement'].astype(str).str.len() > 2]
ndep_long_count = ndep_long.shape[0]
ndep_long_count, ndep_long[['siren','code_departement','code_insee']].head(10)

(637,
           siren code_departement code_insee
 985   219722287              103        228
 1081  219740123              104        412
 1082  219740180              104        418
 1203  219711314              101        131
 1205  219733029              102        997
 1206  219733045              102        304
 1218  219711025              101        102
 1360  219733128              102        312
 1361  219733573              102        357
 1362  219722097              103        996)

In [282]:
insee__after_merge_na = budget_insee['insee_y'].isna().sum()
print(insee__after_merge_na)

KeyError: 'insee_y'

,EXER,NDEPT,INSEE,IDENT,siren,code_departement,code_insee,insee_x,nom_com_x,code_geo,diff,match_insee,insee_y,nom_com_y
0,2021,069,257,21690257700016,216902577,69,257,69257,Vaux-en-Beaujolais,69257,True,True,69257,Vaux-en-Beaujolais
1,2021,069,266,21690266800013,216902668,69,266,69266,Villeurbanne,69266,True,True,69266,Villeurbanne
2,2021,086,213,21860213400015,218602134,86,213,86213,Rouillé,86213,True,True,86213,Rouillé
3,2021,083,97,21830097800010,218300978,83,097,83097,Pourrières,83097,True,True,83097,Pourrières
4,2021,086,221,21860221700018,218602217,86,221,86221,Saint-Genest-d'Ambière,86221,True,True,86221,Saint-Genest-d'Ambière
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989387,2010,40,<NA>,21400190100054,214001901,40,NaN,40190,Monségur,NaN,False,False,40190,Monségur
989388,2010,89,<NA>,21890025600189,218900256,89,NaN,89025,Avallon,NaN,False,False,89025,Avallon
989389,2010,02,<NA>,21020655300062,210206553,02,NaN,02680,Saint-Gobain,NaN,False,False,02680,Saint-Gobain
989390,2010,74,<NA>,21740206400059,217402064,74,NaN,74206,Orcier,NaN,False,False,74206,Orcier
989391,2010,15,<NA>,21150068100047,211500681,15,NaN,NaN,NaN,NaN,False,False,NaN,NaN

In [ ]:
mask_diff = budget_insee['insee_y'].notna() & budget_insee['code_geo'].notna() & (budget_insee['insee_y'] != budget_insee['code_geo'])

# Nombre total
nb_diff = mask_diff.sum()

# 10 exemples
examples_diff = budget_insee.loc[mask_diff, ['siren','NDEPT','insee_y','code_geo','nom_com_y']].head(10)

nb_diff, examples_diff

(np.int64(217283),
         siren NDEPT insee_y code_geo          nom_com_y
 14  218300432   083   83043    83877       Collobrières
 19  217003110   070   70311    70903  Luxeuil-les-Bains
 27  216802090   068   68209    68824         Mittelwihr
 31  212600084   026   26008    26850             Ancône
 33  212401459   024   24145    24966            Creysse
 42  211603691   016   16369    16597            Sigogne
 50  211700869   017   17086    17797           Chaniers
 62  211602859   016   16285    16971            Rougnac
 63  213303001   033   33300    33746     Naujac-sur-Mer
 71  213303340   033   33334    33729            Portets)

In [283]:
nb_diff

np.int64(21692)

In [284]:
mask_diff_ = budget_insee['insee_y'].isna() & budget_insee['code_geo'].notna()
nb_diff = mask_diff_.sum()
examples_diff_ = budget_insee.loc[mask_diff_, ['siren','NDEPT','insee_y','code_geo','nom_com_y']].head(10)

print(nb_diff)

21692
# les exemple montre que ce sont des communes qui ont sesséee d'ou le Nan dans les siren (le fichier siren - code_insee que j'ai mergé datant de 2025)

KeyError: 'insee_y'

In [318]:
budget_insee['match_insee'].value_counts()

match_insee
False    125821
True      69539
Name: count, dtype: int64

In [335]:
budget_insee = budget_insee[['siren', 'code_departement', 'code_insee',
       'insee', 'nom_com', 'code_geo', 'match_insee']]

In [344]:
budget_insee = budget_insee.drop_duplicates()

In [348]:
budget_false = budget_insee.loc[budget_insee['match_insee']==False].drop_duplicates()

In [353]:
budget_false = budget_false.loc[~(budget_false['code_insee'].isna())]

In [ ]:
budget_true[['insee','siren','code_geo']].drop_duplicates()

       insee      siren code_geo
0      69257  216902577    69257
1      69266  216902668    69266
2      86213  218602134    86213
3      83097  218300978    83097
4      86221  218602217    86221
...      ...        ...      ...
86389  95169  200102267    95169
86653  25060  200102259    25060
86987  35062  200102275    35062
88709  49160  200102614    49160
89253  60694  200083483    60694

[34805 rows x 3 columns]

In [347]:
budget_insee['match_insee'].value_counts()

match_insee
False    81700
True     34805
Name: count, dtype: int64

In [356]:
budget_false = budget_false.loc[~(budget_false['insee'].isna())]

In [360]:
budget_false = budget_false[~(budget_false['code_departement'].astype(str).str.len() > 2)]

In [361]:
budget_false.drop_duplicates()

,siren,code_departement,code_insee,insee,nom_com,code_geo,match_insee
14,218300432,83,877,83043,Collobrières,83877,False
19,217003110,70,903,70311,Luxeuil-les-Bains,70903,False
27,216802090,68,824,68209,Mittelwihr,68824,False
31,212600084,26,850,26008,Ancône,26850,False
33,212401459,24,966,24145,Creysse,24966,False
...,...,...,...,...,...,...,...
187127,212203814,22,836,22381,Trézény,22836,False
187128,210101408,01,947,01140,Curtafond,01947,False
187129,215905803,59,959,59580,Steenvoorde,59959,False
187130,212505028,25,910,25502,Roset-Fluans,25910,False
191293,200037646,52,878,52187,Épizon,52878,False

In [366]:
siren_multi_geo = (
    budget_false.groupby('siren')['code_geo']
    .nunique()   # nombre de codes_geo distincts par SIREN
)
nb_siren_multi_geo = (siren_multi_geo > 1).sum()
nb_siren_multi_geo

np.int64(13010)

In [367]:
geo_multi_siren = (
    budget_false.groupby('code_geo')['siren']
    .nunique()   # nombre de SIREN distincts par code_geo
)

nb_geo_multi_siren = (geo_multi_siren > 1).sum()
nb_geo_multi_siren

np.int64(12205)

In [362]:
budget_false['siren'].value_counts()

siren
200054294    28
200060176    25
217500016    25
211002605    25
200055770    24
             ..
214203051     1
215501867     1
212404461     1
212203814     1
200037646     1
Name: count, Length: 20017, dtype: int64

In [363]:
budget_false.loc[budget_false['siren'] == '200054294']

,siren,code_departement,code_insee,insee,nom_com,code_geo,match_insee
3732,200054294,22,003,22046,Le Mené,22003,False
5682,200054294,22,006,22046,Le Mené,22006,False
13681,200054294,22,025,22046,Le Mené,22025,False
20539,200054294,22,009,22046,Le Mené,22009,False
28585,200054294,22,007,22046,Le Mené,22007,False
30433,200054294,22,010,22046,Le Mené,22010,False
38510,200054294,22,013,22046,Le Mené,22013,False
54258,200054294,22,012,22046,Le Mené,22012,False
56552,200054294,22,015,22046,Le Mené,22015,False
57893,200054294,22,011,22046,Le Mené,22011,False
59092,200054294,22,017,22046,Le Mené,22017,False
59483,200054294,22,016,22046,Le Mené,22016,False
67311,200054294,22,569,22046,Le Mené,22569,False
67424,200054294,22,563,22046,Le Mené,22563,False
67507,200054294,22,564,22046,Le Mené,22564,False
67717,200054294,22,565,22046,Le Mené,22565,False
69146,200054294,22,568,22046,Le Mené,22568,False
69173,200054294,22,566,22046,Le Mené,22566,False
75463,200054294,22,004,22046,Le Mené,22004,False
182194,200054294,22,019,22046,Le Mené,22019,False
182216,200054294,22,018,22046,Le Mené,22018,False
182327,200054294,22,014,22046,Le Mené,22014,False
185022,200054294,22,005,22046,Le Mené,22005,False
185454,200054294,22,026,22046,Le Mené,22026,False
185879,200054294,22,028,22046,Le Mené,22028,False
186100,200054294,22,027,22046,Le Mené,22027,False
186592,200054294,22,029,22046,Le Mené,22029,False
186623,200054294,22,002,22046,Le Mené,22002,False

In [60]:
import duckdb
con.close()
con = duckdb.connect("data/dbt_pipeline/dev.duckdb")

In [61]:

df_prime_assurances = con.sql("SELECT * FROM primes_assurances_communes").df()

In [94]:
df_invalid = df_prime_assurances[df_prime_assurances["code_geo"].astype(str).str.len() != 5]

In [97]:
df_invalid

,code_departement,code_insee,siret,siren,annee,code_region,compte,code_geo,code_geo_from_siren,nom_com,solde_debiteur,solde_crediteur,solde
6,08,NaN,21080288000026,210802880,2010,21,616,NaN,08321,Neuville-Day,525.38,0.0,525.38
9,22,NaN,21220363200071,212203632,2010,53,6162,NaN,22363,Trélévern,351.74,0.0,351.74
10,28,NaN,21280375300046,212803753,2010,24,6168,NaN,28375,Serville,522.51,0.0,522.51
11,26,NaN,21260195900035,212601959,2010,82,616,NaN,26195,Montclar-sur-Gervanne,1130.26,0.0,1130.26
13,07,NaN,21070107400069,210701074,2010,82,616,NaN,07107,Jaujac,1000.00,0.0,1000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
707648,09,NaN,21930070400331,219300704,2016,11,6165,NaN,93070,Saint-Ouen-sur-Seine,825.33,0.0,825.33
708346,02,NaN,21200362800113,212003628,2016,94,6168,NaN,2A362,Zonza,4199.86,0.0,4199.86
709076,04,NaN,21420334100091,214203341,2016,84,6161,NaN,42334,Violay,2249.83,0.0,2249.83
709716,02,NaN,21220379800047,212203798,2016,53,6161,NaN,22379,Trévou-Tréguignec,804.72,0.0,804.72
710755,07,NaN,21780551400403,217805514,2017,11,6161,NaN,NaN,NaN,2468.30,0.0,2468.30

In [69]:
df_not_match = df_prime_assurances[df_prime_assurances["code_geo"]!=df_prime_assurances["code_geo_from_siren"]]

In [71]:
df_not_match.loc[(df_not_match['code_geo'].notna()) &(df_not_match['code_geo_from_siren'].notna())]

,code_departement,code_insee,siret,siren,annee,code_region,compte,code_geo,code_geo_from_siren,nom_com,solde_debiteur,solde_crediteur,solde
1,97,650,20000875300010,200008753,2010,6,616,97650,97605,Chiconi,16346.33,0.0,16346.33
1115,97,330,21973304500013,219733045,2010,3,616,97330,97304,Kourou,206768.89,0.0,206768.89
2831,97,651,20000885200010,200008852,2010,6,616,97651,97614,Ouangani,8509.72,0.0,8509.72
3000,97,440,21974008100019,219740081,2010,4,616,97440,97408,La Possession,50802.62,0.0,50802.62
3038,97,111,21971112400012,219711124,2010,1,616,97111,97112,Grand-Bourg,50395.86,0.0,50395.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...
710302,07,989,21740301300048,217403013,2016,84,616,07989,74301,Villard,804.43,0.0,804.43
710303,07,053,21760053500017,217600535,2016,28,6161,07053,76053,Baillolet,1614.92,0.0,1614.92
710304,04,111,21400111700016,214001117,2016,75,6161,04111,40111,Geloux,6662.83,0.0,6662.83
710305,04,202,21400202400013,214002024,2016,75,6161,04202,40202,Narrosse,10037.01,0.0,10037.01
710306,03,530,21330530300017,213305303,2016,75,6161,03530,33530,Teuillac,3837.42,0.0,3837.42

In [72]:
df_prime_assurances.shape

(711549, 13)

In [91]:
df_budget = con.sql("SELECT * FROM budget_per_compte_communes").df()

In [75]:
df_budget.drop_duplicates().shape

(2691326, 13)

In [76]:
df_budget.shape

(2691326, 13)

In [85]:
df_not_match = df_budget[df_budget["code_geo"]!=df_budget["code_geo_from_siren"]]
df_not_match = df_not_match.loc[(df_not_match['code_geo'].notna()) &(df_not_match['code_geo_from_siren'].notna())]

In [86]:
df_not_match

,code_departement,code_insee,siret,siren,annee,code_region,type_compte,code_geo,code_geo_from_siren,nom_com,solde_debiteur,solde_crediteur,solde
57,97,110,21971101700018,219711017,2012,1,produits,97110,97101,Les Abymes,0.00,82381098.99,-82381098.99
58,97,221,21972217000012,219722170,2012,2,produits,97221,97217,Le Marin,0.00,10580971.98,-10580971.98
632,97,110,21971108200012,219711082,2013,1,produits,97110,97108,Capesterre-de-Marie-Galante,227325.06,4154589.36,-3927264.30
633,97,221,21972211300012,219722113,2013,2,produits,97221,97211,Grand'Rivière,33180.00,1132554.07,-1099374.07
1243,97,111,21971112400012,219711124,2014,1,produits,97111,97112,Grand-Bourg,0.00,9809500.87,-9809500.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2689856,97,650,20000879500011,200008795,2011,6,primes d assurances,97650,97608,Dzaoudzi,6448.81,0.00,6448.81
2690404,97,113,21971131400019,219711314,2012,1,primes d assurances,97113,97131,Terre-de-Haut,31122.55,0.00,31122.55
2690405,97,661,20000883700011,200008837,2012,6,primes d assurances,97661,97611,Mamoudzou,32631.86,0.00,32631.86
2690964,97,440,21974004000015,219740040,2013,4,primes d assurances,97440,97404,L'Étang-Salé,1033.88,0.00,1033.88
2690965,97,661,20000887800015,200008878,2013,6,primes d assurances,97661,97616,Sada,10807.13,0.00,10807.13

In [87]:
df_invalid_ = df_budget[df_budget["code_geo"].astype(str).str.len() != 5]

In [93]:
df_budget

,code_departement,code_insee,siret,siren,annee,code_region,type_compte,code_geo,code_geo_from_siren,nom_com,solde_debiteur,solde_crediteur,solde
0,80,832,21800779700010,218007797,2012,32,produits,80832,80832,Yvrench,0.00,170966.83,-170966.83
1,81,023,21810023800011,218100238,2012,76,produits,81023,81023,Barre,639.00,226204.63,-225565.63
2,81,027,21810027900015,218100279,2012,76,produits,81027,81027,Belleserre,0.00,142234.50,-142234.50
3,81,285,21810285300015,218102853,2012,76,produits,81285,81285,Sérénac,0.00,313157.38,-313157.38
4,81,303,21810303400011,218103034,2012,76,produits,81303,81303,Trébas,0.00,344061.45,-344061.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2691321,56,213,21560213700014,215602137,2012,53,primes d assurances,56213,NaN,NaN,7206.35,0.00,7206.35
2691322,57,439,21570439600013,215704396,2012,44,primes d assurances,57439,NaN,NaN,3490.20,0.00,3490.20
2691323,41,011,21410011700016,214100117,2014,24,primes d assurances,41011,NaN,NaN,1079.03,0.00,1079.03
2691324,42,291,21420291300015,214202913,2014,84,primes d assurances,42291,NaN,NaN,4234.14,0.00,4234.14
2691325,52,064,21520044500017,215200445,2014,44,primes d assurances,52064,NaN,NaN,9644.18,0.00,9644.18

In [155]:
prime_assurance_ = pd.read_csv('Documents/GitHub/14_PrixChangementClimatique/data/dbt_pipeline/pipeline_inputs/primes_assurances_communes_clean.csv')

In [160]:
budget_per_compte_communes_clean = pd.read_csv('Documents/GitHub/14_PrixChangementClimatique/data/dbt_pipeline/pipeline_inputs/budget_per_compte_communes_clean.csv')

In [164]:
prime_assurance_ = prime_assurance_.drop('Unnamed: 0',axis=1).set_index('EXER',drop=True)

In [167]:
prime_assurance_.to_csv('Documents/GitHub/14_PrixChangementClimatique/data/dbt_pipeline/pipeline_inputs/primes_assurances_communes_clean.csv',quoting=1)
budget_per_compte_communes_clean.to_csv('Documents/GitHub/14_PrixChangementClimatique/data/dbt_pipeline/pipeline_inputs/budget_per_compte_communes_clean.csv',quoting=1)

In [166]:
prime_assurance_

     NDEPT  CREGI  INSEE  COMPTE           IDENT        SD   SC
EXER
2021    17     75     35    6161  21170035600010   1618.92  0.0
2021     2     32     32    6168  21020032500012    866.22  0.0
2021    55     44    504    6161  21550504100016   5138.16  0.0
2021    57     44     58    6161  21570058400208  46737.03  0.0
2021    86     75    182    6168  21860182100018    694.00  0.0
...    ...    ...    ...     ...             ...       ...  ...
2010    40     72    240     616  21400240400017   6806.36  0.0
2010    84     93      5     616  21840005900018   1829.45  0.0
2010    84     93    112     616  21840112300011   9424.80  0.0
2010    78     11     82     616  21780082000011   3125.73  0.0
2010     1     82  empty     616  21010343800037   1873.02  0.0

[711549 rows x 7 columns]

In [163]:
budget_per_compte_communes_clean = budget_per_compte_communes_clean.drop('Unnamed: 0',axis=1).set_index('EXER',drop=True)

In [ ]:
budget_per_compte_communes_clean

In [161]:
budget_per_compte_communes_clean.dtypes

Unnamed: 0       int64
EXER             int64
NDEPT              str
CREGI            int64
INSEE              str
IDENT            int64
SD             float64
SC             float64
type_compte        str
dtype: object

In [ ]:
print(prime_assurance_.dtypes)

Unnamed: 0      int64
EXER            int64
NDEPT             str
CREGI           int64
INSEE             str
COMPTE          int64
IDENT           int64
SD            float64
SC            float64
dtype: object

In [ ]:
budg = pd.read_csv('Documents/GitHUb/')